// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pay.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.pay;

/**
 * Protobuf type {@code com.iqexception.fxhelper.api.rest.pay.DepositResult}
 */
public final class DepositResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iqexception.fxhelper.api.rest.pay.DepositResult)
    DepositResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DepositResult.newBuilder() to construct.
  private DepositResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DepositResult() {
    appId_ = "";
    timeStamp_ = "";
    nonceStr_ = "";
    signType_ = "";
    paySign_ = "";
    package_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DepositResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iqexception.fxhelper.api.rest.pay.PayRest.internal_static_com_iqexception_fxhelper_api_rest_pay_DepositResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iqexception.fxhelper.api.rest.pay.PayRest.internal_static_com_iqexception_fxhelper_api_rest_pay_DepositResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iqexception.fxhelper.api.rest.pay.DepositResult.class, com.iqexception.fxhelper.api.rest.pay.DepositResult.Builder.class);
  }

  private int bitField0_;
  public static final int APP_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appId_ = "";
  /**
   * <code>optional string app_id = 1;</code>
   * @return Whether the appId field is set.
   */
  @java.lang.Override
  public boolean hasAppId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string app_id = 1;</code>
   * @return The appId.
   */
  @java.lang.Override
  public java.lang.String getAppId() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string app_id = 1;</code>
   * @return The bytes for appId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_STAMP_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timeStamp_ = "";
  /**
   * <code>optional string time_stamp = 2;</code>
   * @return Whether the timeStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string time_stamp = 2;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public java.lang.String getTimeStamp() {
    java.lang.Object ref = timeStamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeStamp_ = s;
      return s;
    }
  }
  /**
   * <code>optional string time_stamp = 2;</code>
   * @return The bytes for timeStamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeStampBytes() {
    java.lang.Object ref = timeStamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeStamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NONCE_STR_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nonceStr_ = "";
  /**
   * <code>optional string nonce_str = 3;</code>
   * @return Whether the nonceStr field is set.
   */
  @java.lang.Override
  public boolean hasNonceStr() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string nonce_str = 3;</code>
   * @return The nonceStr.
   */
  @java.lang.Override
  public java.lang.String getNonceStr() {
    java.lang.Object ref = nonceStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nonceStr_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nonce_str = 3;</code>
   * @return The bytes for nonceStr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNonceStrBytes() {
    java.lang.Object ref = nonceStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nonceStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGN_TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object signType_ = "";
  /**
   * <code>optional string sign_type = 4;</code>
   * @return Whether the signType field is set.
   */
  @java.lang.Override
  public boolean hasSignType() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string sign_type = 4;</code>
   * @return The signType.
   */
  @java.lang.Override
  public java.lang.String getSignType() {
    java.lang.Object ref = signType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      signType_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sign_type = 4;</code>
   * @return The bytes for signType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSignTypeBytes() {
    java.lang.Object ref = signType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAY_SIGN_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object paySign_ = "";
  /**
   * <code>optional string pay_sign = 5;</code>
   * @return Whether the paySign field is set.
   */
  @java.lang.Override
  public boolean hasPaySign() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string pay_sign = 5;</code>
   * @return The paySign.
   */
  @java.lang.Override
  public java.lang.String getPaySign() {
    java.lang.Object ref = paySign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paySign_ = s;
      return s;
    }
  }
  /**
   * <code>optional string pay_sign = 5;</code>
   * @return The bytes for paySign.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPaySignBytes() {
    java.lang.Object ref = paySign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paySign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object package_ = "";
  /**
   * <code>optional string package = 6;</code>
   * @return Whether the package field is set.
   */
  @java.lang.Override
  public boolean hasPackage() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string package = 6;</code>
   * @return The package.
   */
  @java.lang.Override
  public java.lang.String getPackage() {
    java.lang.Object ref = package_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      package_ = s;
      return s;
    }
  }
  /**
   * <code>optional string package = 6;</code>
   * @return The bytes for package.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageBytes() {
    java.lang.Object ref = package_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      package_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeStamp_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nonceStr_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, signType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, paySign_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, package_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeStamp_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nonceStr_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, signType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, paySign_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, package_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iqexception.fxhelper.api.rest.pay.DepositResult)) {
      return super.equals(obj);
    }
    com.iqexception.fxhelper.api.rest.pay.DepositResult other = (com.iqexception.fxhelper.api.rest.pay.DepositResult) obj;

    if (hasAppId() != other.hasAppId()) return false;
    if (hasAppId()) {
      if (!getAppId()
          .equals(other.getAppId())) return false;
    }
    if (hasTimeStamp() != other.hasTimeStamp()) return false;
    if (hasTimeStamp()) {
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
    }
    if (hasNonceStr() != other.hasNonceStr()) return false;
    if (hasNonceStr()) {
      if (!getNonceStr()
          .equals(other.getNonceStr())) return false;
    }
    if (hasSignType() != other.hasSignType()) return false;
    if (hasSignType()) {
      if (!getSignType()
          .equals(other.getSignType())) return false;
    }
    if (hasPaySign() != other.hasPaySign()) return false;
    if (hasPaySign()) {
      if (!getPaySign()
          .equals(other.getPaySign())) return false;
    }
    if (hasPackage() != other.hasPackage()) return false;
    if (hasPackage()) {
      if (!getPackage()
          .equals(other.getPackage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAppId()) {
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
    }
    if (hasTimeStamp()) {
      hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
    }
    if (hasNonceStr()) {
      hash = (37 * hash) + NONCE_STR_FIELD_NUMBER;
      hash = (53 * hash) + getNonceStr().hashCode();
    }
    if (hasSignType()) {
      hash = (37 * hash) + SIGN_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSignType().hashCode();
    }
    if (hasPaySign()) {
      hash = (37 * hash) + PAY_SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getPaySign().hashCode();
    }
    if (hasPackage()) {
      hash = (37 * hash) + PACKAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPackage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.rest.pay.DepositResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iqexception.fxhelper.api.rest.pay.DepositResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iqexception.fxhelper.api.rest.pay.DepositResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iqexception.fxhelper.api.rest.pay.DepositResult)
      com.iqexception.fxhelper.api.rest.pay.DepositResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iqexception.fxhelper.api.rest.pay.PayRest.internal_static_com_iqexception_fxhelper_api_rest_pay_DepositResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iqexception.fxhelper.api.rest.pay.PayRest.internal_static_com_iqexception_fxhelper_api_rest_pay_DepositResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iqexception.fxhelper.api.rest.pay.DepositResult.class, com.iqexception.fxhelper.api.rest.pay.DepositResult.Builder.class);
    }

    // Construct using com.iqexception.fxhelper.api.rest.pay.DepositResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      appId_ = "";
      timeStamp_ = "";
      nonceStr_ = "";
      signType_ = "";
      paySign_ = "";
      package_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iqexception.fxhelper.api.rest.pay.PayRest.internal_static_com_iqexception_fxhelper_api_rest_pay_DepositResult_descriptor;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.pay.DepositResult getDefaultInstanceForType() {
      return com.iqexception.fxhelper.api.rest.pay.DepositResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.pay.DepositResult build() {
      com.iqexception.fxhelper.api.rest.pay.DepositResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.pay.DepositResult buildPartial() {
      com.iqexception.fxhelper.api.rest.pay.DepositResult result = new com.iqexception.fxhelper.api.rest.pay.DepositResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.iqexception.fxhelper.api.rest.pay.DepositResult result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.appId_ = appId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timeStamp_ = timeStamp_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nonceStr_ = nonceStr_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.signType_ = signType_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.paySign_ = paySign_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.package_ = package_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iqexception.fxhelper.api.rest.pay.DepositResult) {
        return mergeFrom((com.iqexception.fxhelper.api.rest.pay.DepositResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iqexception.fxhelper.api.rest.pay.DepositResult other) {
      if (other == com.iqexception.fxhelper.api.rest.pay.DepositResult.getDefaultInstance()) return this;
      if (other.hasAppId()) {
        appId_ = other.appId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasTimeStamp()) {
        timeStamp_ = other.timeStamp_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasNonceStr()) {
        nonceStr_ = other.nonceStr_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasSignType()) {
        signType_ = other.signType_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasPaySign()) {
        paySign_ = other.paySign_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasPackage()) {
        package_ = other.package_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              appId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              timeStamp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              nonceStr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              signType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              paySign_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              package_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object appId_ = "";
    /**
     * <code>optional string app_id = 1;</code>
     * @return Whether the appId field is set.
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string app_id = 1;</code>
     * @return The appId.
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string app_id = 1;</code>
     * @return The bytes for appId.
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string app_id = 1;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string app_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      appId_ = getDefaultInstance().getAppId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string app_id = 1;</code>
     * @param value The bytes for appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object timeStamp_ = "";
    /**
     * <code>optional string time_stamp = 2;</code>
     * @return Whether the timeStamp field is set.
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string time_stamp = 2;</code>
     * @return The timeStamp.
     */
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string time_stamp = 2;</code>
     * @return The bytes for timeStamp.
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string time_stamp = 2;</code>
     * @param value The timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStamp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timeStamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string time_stamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeStamp() {
      timeStamp_ = getDefaultInstance().getTimeStamp();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string time_stamp = 2;</code>
     * @param value The bytes for timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timeStamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object nonceStr_ = "";
    /**
     * <code>optional string nonce_str = 3;</code>
     * @return Whether the nonceStr field is set.
     */
    public boolean hasNonceStr() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string nonce_str = 3;</code>
     * @return The nonceStr.
     */
    public java.lang.String getNonceStr() {
      java.lang.Object ref = nonceStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nonceStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nonce_str = 3;</code>
     * @return The bytes for nonceStr.
     */
    public com.google.protobuf.ByteString
        getNonceStrBytes() {
      java.lang.Object ref = nonceStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonceStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nonce_str = 3;</code>
     * @param value The nonceStr to set.
     * @return This builder for chaining.
     */
    public Builder setNonceStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nonceStr_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce_str = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonceStr() {
      nonceStr_ = getDefaultInstance().getNonceStr();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce_str = 3;</code>
     * @param value The bytes for nonceStr to set.
     * @return This builder for chaining.
     */
    public Builder setNonceStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nonceStr_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object signType_ = "";
    /**
     * <code>optional string sign_type = 4;</code>
     * @return Whether the signType field is set.
     */
    public boolean hasSignType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string sign_type = 4;</code>
     * @return The signType.
     */
    public java.lang.String getSignType() {
      java.lang.Object ref = signType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sign_type = 4;</code>
     * @return The bytes for signType.
     */
    public com.google.protobuf.ByteString
        getSignTypeBytes() {
      java.lang.Object ref = signType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sign_type = 4;</code>
     * @param value The signType to set.
     * @return This builder for chaining.
     */
    public Builder setSignType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      signType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sign_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignType() {
      signType_ = getDefaultInstance().getSignType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string sign_type = 4;</code>
     * @param value The bytes for signType to set.
     * @return This builder for chaining.
     */
    public Builder setSignTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      signType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object paySign_ = "";
    /**
     * <code>optional string pay_sign = 5;</code>
     * @return Whether the paySign field is set.
     */
    public boolean hasPaySign() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string pay_sign = 5;</code>
     * @return The paySign.
     */
    public java.lang.String getPaySign() {
      java.lang.Object ref = paySign_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paySign_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string pay_sign = 5;</code>
     * @return The bytes for paySign.
     */
    public com.google.protobuf.ByteString
        getPaySignBytes() {
      java.lang.Object ref = paySign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paySign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string pay_sign = 5;</code>
     * @param value The paySign to set.
     * @return This builder for chaining.
     */
    public Builder setPaySign(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      paySign_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string pay_sign = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaySign() {
      paySign_ = getDefaultInstance().getPaySign();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string pay_sign = 5;</code>
     * @param value The bytes for paySign to set.
     * @return This builder for chaining.
     */
    public Builder setPaySignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      paySign_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object package_ = "";
    /**
     * <code>optional string package = 6;</code>
     * @return Whether the package field is set.
     */
    public boolean hasPackage() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string package = 6;</code>
     * @return The package.
     */
    public java.lang.String getPackage() {
      java.lang.Object ref = package_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        package_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string package = 6;</code>
     * @return The bytes for package.
     */
    public com.google.protobuf.ByteString
        getPackageBytes() {
      java.lang.Object ref = package_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        package_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string package = 6;</code>
     * @param value The package to set.
     * @return This builder for chaining.
     */
    public Builder setPackage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      package_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string package = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackage() {
      package_ = getDefaultInstance().getPackage();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string package = 6;</code>
     * @param value The bytes for package to set.
     * @return This builder for chaining.
     */
    public Builder setPackageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      package_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.iqexception.fxhelper.api.rest.pay.DepositResult)
  }

  // @@protoc_insertion_point(class_scope:com.iqexception.fxhelper.api.rest.pay.DepositResult)
  private static final com.iqexception.fxhelper.api.rest.pay.DepositResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iqexception.fxhelper.api.rest.pay.DepositResult();
  }

  public static com.iqexception.fxhelper.api.rest.pay.DepositResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DepositResult>
      PARSER = new com.google.protobuf.AbstractParser<DepositResult>() {
    @java.lang.Override
    public DepositResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DepositResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DepositResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iqexception.fxhelper.api.rest.pay.DepositResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

