/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.order.dal.generator;


import com.iqexception.fxhelper.order.dal.generator.tables.FxOrder;
import com.iqexception.fxhelper.order.dal.generator.tables.records.FxOrderRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FxOrderRecord> KEY_FX_ORDER_FX_ORDER_IDX_SHOP_ID__SERIAL_NO = Internal.createUniqueKey(FxOrder.FX_ORDER, DSL.name("KEY_fx_order_fx_order_idx_shop_id__serial_no"), new TableField[] { FxOrder.FX_ORDER.SHOP_ID, FxOrder.FX_ORDER.SERIAL_NO }, true);
    public static final UniqueKey<FxOrderRecord> KEY_FX_ORDER_PRIMARY = Internal.createUniqueKey(FxOrder.FX_ORDER, DSL.name("KEY_fx_order_PRIMARY"), new TableField[] { FxOrder.FX_ORDER.ID }, true);
}
