syntax = "proto3";
option java_multiple_files = true;
import "common.proto";
import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";
package com.iqexception.fxhelper.api.rest.order;

service OrderRestService{
  rpc createOrder(CreateOrderRequest) returns (CreateOrderResponse);
  rpc payOrder(PayOrderRequest) returns (common.BaseResponse);
}

message CreateOrderRequest{
  common.MobileRequestHead head = 1 [(buf.validate.field).required = true];
  CreateOrderParam param = 2 [(buf.validate.field).required = true];
}
message CreateOrderParam{
  optional int64 shop_id = 1 [(buf.validate.field).required = true, (buf.validate.field).int64.gt = 0];
  optional string capture = 2 [(buf.validate.field).required = true, (buf.validate.field).string.min_len = 1];
  optional string serial_no = 3 [(buf.validate.field).required = true, (buf.validate.field).string.min_len = 1];
}
message CreateOrderResponse{
  common.ResponseStatus status = 1;
  CreateOrderResult result = 2;
}
message CreateOrderResult{
  optional int64 order_id = 1;
}


message PayOrderRequest{
  common.MobileRequestHead head = 1 [(buf.validate.field).required = true];
  PayOrderParam param = 2 [(buf.validate.field).required = true];
}
message PayOrderParam{
  optional int64 order_id = 1 [(buf.validate.field).required = true, (buf.validate.field).int64.gt = 0];
}
