// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.common;

public interface BaseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.common.BaseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1 [(.buf.validate.field) = { ... }</code>
   * @return The status.
   */
  com.iqexception.fxhelper.api.common.ResponseStatus getStatus();
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1 [(.buf.validate.field) = { ... }</code>
   */
  com.iqexception.fxhelper.api.common.ResponseStatusOrBuilder getStatusOrBuilder();
}
