// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.user;

public interface LoginParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.user.LoginParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string code = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the code field is set.
   */
  boolean hasCode();
  /**
   * <code>optional string code = 1 [(.buf.validate.field) = { ... }</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>optional string code = 1 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
