// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.user;

public interface LoginResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.user.LoginResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string token = 1;</code>
   * @return Whether the token field is set.
   */
  boolean hasToken();
  /**
   * <code>optional string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>optional bool new_user = 2;</code>
   * @return Whether the newUser field is set.
   */
  boolean hasNewUser();
  /**
   * <code>optional bool new_user = 2;</code>
   * @return The newUser.
   */
  boolean getNewUser();
}
