// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.user;

public final class UserRest {
  private UserRest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_user_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_user_LoginParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_user_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_user_LoginResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_user_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_user_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017user.rest.proto\022&com.iqexception.fxhel" +
      "per.api.rest.user\032\014common.proto\032\033google/" +
      "protobuf/empty.proto\032\033buf/validate/valid" +
      "ate.proto\"\247\001\n\014LoginRequest\022L\n\004head\030\001 \001(\013" +
      "26.com.iqexception.fxhelper.api.common.M" +
      "obileRequestHeadB\006\272H\003\310\001\001\022I\n\005param\030\002 \001(\0132" +
      "2.com.iqexception.fxhelper.api.rest.user" +
      ".LoginParamB\006\272H\003\310\001\001\"4\n\nLoginParam\022\035\n\004cod" +
      "e\030\001 \001(\tB\n\272H\007r\002\020\001\310\001\001H\000\210\001\001B\007\n\005_code\"\231\001\n\rLo" +
      "ginResponse\022C\n\006status\030\001 \001(\01323.com.iqexce" +
      "ption.fxhelper.api.common.ResponseStatus" +
      "\022C\n\006result\030\002 \001(\01323.com.iqexception.fxhel" +
      "per.api.rest.user.LoginResult\"O\n\013LoginRe" +
      "sult\022\022\n\005token\030\001 \001(\tH\000\210\001\001\022\025\n\010new_user\030\002 \001" +
      "(\010H\001\210\001\001B\010\n\006_tokenB\013\n\t_new_user\"-\n\rHelloR" +
      "esponse\022\022\n\005reply\030\001 \001(\tH\000\210\001\001B\010\n\006_replyB\002P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.iqexception.fxhelper.api.common.Common.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_user_LoginRequest_descriptor,
        new java.lang.String[] { "Head", "Param", });
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginParam_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_user_LoginParam_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_user_LoginResponse_descriptor,
        new java.lang.String[] { "Status", "Result", });
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_iqexception_fxhelper_api_rest_user_LoginResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_user_LoginResult_descriptor,
        new java.lang.String[] { "Token", "NewUser", });
    internal_static_com_iqexception_fxhelper_api_rest_user_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_iqexception_fxhelper_api_rest_user_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_user_HelloResponse_descriptor,
        new java.lang.String[] { "Reply", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.iqexception.fxhelper.api.common.Common.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
