// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.shop;

public interface GetShopListResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.shop.GetShopListResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  java.util.List<com.iqexception.fxhelper.api.shop.ShopInfo> 
      getShopInfosList();
  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  com.iqexception.fxhelper.api.shop.ShopInfo getShopInfos(int index);
  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  int getShopInfosCount();
  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  java.util.List<? extends com.iqexception.fxhelper.api.shop.ShopInfoOrBuilder> 
      getShopInfosOrBuilderList();
  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  com.iqexception.fxhelper.api.shop.ShopInfoOrBuilder getShopInfosOrBuilder(
      int index);
}
