// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.shop;

public interface GetShopListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.shop.GetShopListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 shop_ids = 1 [(.buf.validate.field) = { ... }</code>
   * @return A list containing the shopIds.
   */
  java.util.List<java.lang.Long> getShopIdsList();
  /**
   * <code>repeated int64 shop_ids = 1 [(.buf.validate.field) = { ... }</code>
   * @return The count of shopIds.
   */
  int getShopIdsCount();
  /**
   * <code>repeated int64 shop_ids = 1 [(.buf.validate.field) = { ... }</code>
   * @param index The index of the element to return.
   * @return The shopIds at the given index.
   */
  long getShopIds(int index);
}
