// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.shop;

/**
 * Protobuf type {@code com.iqexception.fxhelper.api.shop.GetUserShopListResult}
 */
public final class GetUserShopListResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iqexception.fxhelper.api.shop.GetUserShopListResult)
    GetUserShopListResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetUserShopListResult.newBuilder() to construct.
  private GetUserShopListResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetUserShopListResult() {
    shopInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetUserShopListResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iqexception.fxhelper.api.shop.Shop.internal_static_com_iqexception_fxhelper_api_shop_GetUserShopListResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iqexception.fxhelper.api.shop.Shop.internal_static_com_iqexception_fxhelper_api_shop_GetUserShopListResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iqexception.fxhelper.api.shop.GetUserShopListResult.class, com.iqexception.fxhelper.api.shop.GetUserShopListResult.Builder.class);
  }

  public static final int SHOP_INFOS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.iqexception.fxhelper.api.shop.ShopInfo> shopInfos_;
  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.iqexception.fxhelper.api.shop.ShopInfo> getShopInfosList() {
    return shopInfos_;
  }
  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.iqexception.fxhelper.api.shop.ShopInfoOrBuilder> 
      getShopInfosOrBuilderList() {
    return shopInfos_;
  }
  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  @java.lang.Override
  public int getShopInfosCount() {
    return shopInfos_.size();
  }
  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.shop.ShopInfo getShopInfos(int index) {
    return shopInfos_.get(index);
  }
  /**
   * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.shop.ShopInfoOrBuilder getShopInfosOrBuilder(
      int index) {
    return shopInfos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < shopInfos_.size(); i++) {
      output.writeMessage(1, shopInfos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < shopInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, shopInfos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iqexception.fxhelper.api.shop.GetUserShopListResult)) {
      return super.equals(obj);
    }
    com.iqexception.fxhelper.api.shop.GetUserShopListResult other = (com.iqexception.fxhelper.api.shop.GetUserShopListResult) obj;

    if (!getShopInfosList()
        .equals(other.getShopInfosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getShopInfosCount() > 0) {
      hash = (37 * hash) + SHOP_INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getShopInfosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iqexception.fxhelper.api.shop.GetUserShopListResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iqexception.fxhelper.api.shop.GetUserShopListResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iqexception.fxhelper.api.shop.GetUserShopListResult)
      com.iqexception.fxhelper.api.shop.GetUserShopListResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iqexception.fxhelper.api.shop.Shop.internal_static_com_iqexception_fxhelper_api_shop_GetUserShopListResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iqexception.fxhelper.api.shop.Shop.internal_static_com_iqexception_fxhelper_api_shop_GetUserShopListResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iqexception.fxhelper.api.shop.GetUserShopListResult.class, com.iqexception.fxhelper.api.shop.GetUserShopListResult.Builder.class);
    }

    // Construct using com.iqexception.fxhelper.api.shop.GetUserShopListResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (shopInfosBuilder_ == null) {
        shopInfos_ = java.util.Collections.emptyList();
      } else {
        shopInfos_ = null;
        shopInfosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iqexception.fxhelper.api.shop.Shop.internal_static_com_iqexception_fxhelper_api_shop_GetUserShopListResult_descriptor;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.shop.GetUserShopListResult getDefaultInstanceForType() {
      return com.iqexception.fxhelper.api.shop.GetUserShopListResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.shop.GetUserShopListResult build() {
      com.iqexception.fxhelper.api.shop.GetUserShopListResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.shop.GetUserShopListResult buildPartial() {
      com.iqexception.fxhelper.api.shop.GetUserShopListResult result = new com.iqexception.fxhelper.api.shop.GetUserShopListResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.iqexception.fxhelper.api.shop.GetUserShopListResult result) {
      if (shopInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          shopInfos_ = java.util.Collections.unmodifiableList(shopInfos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.shopInfos_ = shopInfos_;
      } else {
        result.shopInfos_ = shopInfosBuilder_.build();
      }
    }

    private void buildPartial0(com.iqexception.fxhelper.api.shop.GetUserShopListResult result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iqexception.fxhelper.api.shop.GetUserShopListResult) {
        return mergeFrom((com.iqexception.fxhelper.api.shop.GetUserShopListResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iqexception.fxhelper.api.shop.GetUserShopListResult other) {
      if (other == com.iqexception.fxhelper.api.shop.GetUserShopListResult.getDefaultInstance()) return this;
      if (shopInfosBuilder_ == null) {
        if (!other.shopInfos_.isEmpty()) {
          if (shopInfos_.isEmpty()) {
            shopInfos_ = other.shopInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureShopInfosIsMutable();
            shopInfos_.addAll(other.shopInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.shopInfos_.isEmpty()) {
          if (shopInfosBuilder_.isEmpty()) {
            shopInfosBuilder_.dispose();
            shopInfosBuilder_ = null;
            shopInfos_ = other.shopInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            shopInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getShopInfosFieldBuilder() : null;
          } else {
            shopInfosBuilder_.addAllMessages(other.shopInfos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.iqexception.fxhelper.api.shop.ShopInfo m =
                  input.readMessage(
                      com.iqexception.fxhelper.api.shop.ShopInfo.parser(),
                      extensionRegistry);
              if (shopInfosBuilder_ == null) {
                ensureShopInfosIsMutable();
                shopInfos_.add(m);
              } else {
                shopInfosBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.iqexception.fxhelper.api.shop.ShopInfo> shopInfos_ =
      java.util.Collections.emptyList();
    private void ensureShopInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        shopInfos_ = new java.util.ArrayList<com.iqexception.fxhelper.api.shop.ShopInfo>(shopInfos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.iqexception.fxhelper.api.shop.ShopInfo, com.iqexception.fxhelper.api.shop.ShopInfo.Builder, com.iqexception.fxhelper.api.shop.ShopInfoOrBuilder> shopInfosBuilder_;

    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public java.util.List<com.iqexception.fxhelper.api.shop.ShopInfo> getShopInfosList() {
      if (shopInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(shopInfos_);
      } else {
        return shopInfosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public int getShopInfosCount() {
      if (shopInfosBuilder_ == null) {
        return shopInfos_.size();
      } else {
        return shopInfosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.shop.ShopInfo getShopInfos(int index) {
      if (shopInfosBuilder_ == null) {
        return shopInfos_.get(index);
      } else {
        return shopInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public Builder setShopInfos(
        int index, com.iqexception.fxhelper.api.shop.ShopInfo value) {
      if (shopInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShopInfosIsMutable();
        shopInfos_.set(index, value);
        onChanged();
      } else {
        shopInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public Builder setShopInfos(
        int index, com.iqexception.fxhelper.api.shop.ShopInfo.Builder builderForValue) {
      if (shopInfosBuilder_ == null) {
        ensureShopInfosIsMutable();
        shopInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        shopInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public Builder addShopInfos(com.iqexception.fxhelper.api.shop.ShopInfo value) {
      if (shopInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShopInfosIsMutable();
        shopInfos_.add(value);
        onChanged();
      } else {
        shopInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public Builder addShopInfos(
        int index, com.iqexception.fxhelper.api.shop.ShopInfo value) {
      if (shopInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShopInfosIsMutable();
        shopInfos_.add(index, value);
        onChanged();
      } else {
        shopInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public Builder addShopInfos(
        com.iqexception.fxhelper.api.shop.ShopInfo.Builder builderForValue) {
      if (shopInfosBuilder_ == null) {
        ensureShopInfosIsMutable();
        shopInfos_.add(builderForValue.build());
        onChanged();
      } else {
        shopInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public Builder addShopInfos(
        int index, com.iqexception.fxhelper.api.shop.ShopInfo.Builder builderForValue) {
      if (shopInfosBuilder_ == null) {
        ensureShopInfosIsMutable();
        shopInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        shopInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public Builder addAllShopInfos(
        java.lang.Iterable<? extends com.iqexception.fxhelper.api.shop.ShopInfo> values) {
      if (shopInfosBuilder_ == null) {
        ensureShopInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, shopInfos_);
        onChanged();
      } else {
        shopInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public Builder clearShopInfos() {
      if (shopInfosBuilder_ == null) {
        shopInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        shopInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public Builder removeShopInfos(int index) {
      if (shopInfosBuilder_ == null) {
        ensureShopInfosIsMutable();
        shopInfos_.remove(index);
        onChanged();
      } else {
        shopInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.shop.ShopInfo.Builder getShopInfosBuilder(
        int index) {
      return getShopInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.shop.ShopInfoOrBuilder getShopInfosOrBuilder(
        int index) {
      if (shopInfosBuilder_ == null) {
        return shopInfos_.get(index);  } else {
        return shopInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public java.util.List<? extends com.iqexception.fxhelper.api.shop.ShopInfoOrBuilder> 
         getShopInfosOrBuilderList() {
      if (shopInfosBuilder_ != null) {
        return shopInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(shopInfos_);
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.shop.ShopInfo.Builder addShopInfosBuilder() {
      return getShopInfosFieldBuilder().addBuilder(
          com.iqexception.fxhelper.api.shop.ShopInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.shop.ShopInfo.Builder addShopInfosBuilder(
        int index) {
      return getShopInfosFieldBuilder().addBuilder(
          index, com.iqexception.fxhelper.api.shop.ShopInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.shop.ShopInfo shop_infos = 1;</code>
     */
    public java.util.List<com.iqexception.fxhelper.api.shop.ShopInfo.Builder> 
         getShopInfosBuilderList() {
      return getShopInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.iqexception.fxhelper.api.shop.ShopInfo, com.iqexception.fxhelper.api.shop.ShopInfo.Builder, com.iqexception.fxhelper.api.shop.ShopInfoOrBuilder> 
        getShopInfosFieldBuilder() {
      if (shopInfosBuilder_ == null) {
        shopInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.iqexception.fxhelper.api.shop.ShopInfo, com.iqexception.fxhelper.api.shop.ShopInfo.Builder, com.iqexception.fxhelper.api.shop.ShopInfoOrBuilder>(
                shopInfos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        shopInfos_ = null;
      }
      return shopInfosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.iqexception.fxhelper.api.shop.GetUserShopListResult)
  }

  // @@protoc_insertion_point(class_scope:com.iqexception.fxhelper.api.shop.GetUserShopListResult)
  private static final com.iqexception.fxhelper.api.shop.GetUserShopListResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iqexception.fxhelper.api.shop.GetUserShopListResult();
  }

  public static com.iqexception.fxhelper.api.shop.GetUserShopListResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUserShopListResult>
      PARSER = new com.google.protobuf.AbstractParser<GetUserShopListResult>() {
    @java.lang.Override
    public GetUserShopListResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetUserShopListResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserShopListResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iqexception.fxhelper.api.shop.GetUserShopListResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

