// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.shop;

public interface GetUserShopListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.shop.GetUserShopListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 user_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional int64 user_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return The userId.
   */
  long getUserId();
}
