// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.shop;

/**
 * Protobuf type {@code com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam}
 */
public final class GetQrCodesParam extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam)
    GetQrCodesParamOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetQrCodesParam.newBuilder() to construct.
  private GetQrCodesParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetQrCodesParam() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetQrCodesParam();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesParam_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesParam_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.class, com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.Builder.class);
  }

  private int bitField0_;
  public static final int SHOP_ID_FIELD_NUMBER = 1;
  private long shopId_ = 0L;
  /**
   * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the shopId field is set.
   */
  @java.lang.Override
  public boolean hasShopId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return The shopId.
   */
  @java.lang.Override
  public long getShopId() {
    return shopId_;
  }

  public static final int NUMBER_FIELD_NUMBER = 2;
  private long number_ = 0L;
  /**
   * <code>optional int64 number = 2 [(.buf.validate.field) = { ... }</code>
   * @return Whether the number field is set.
   */
  @java.lang.Override
  public boolean hasNumber() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 number = 2 [(.buf.validate.field) = { ... }</code>
   * @return The number.
   */
  @java.lang.Override
  public long getNumber() {
    return number_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, shopId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, number_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, shopId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, number_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam)) {
      return super.equals(obj);
    }
    com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam other = (com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam) obj;

    if (hasShopId() != other.hasShopId()) return false;
    if (hasShopId()) {
      if (getShopId()
          != other.getShopId()) return false;
    }
    if (hasNumber() != other.hasNumber()) return false;
    if (hasNumber()) {
      if (getNumber()
          != other.getNumber()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasShopId()) {
      hash = (37 * hash) + SHOP_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getShopId());
    }
    if (hasNumber()) {
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumber());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam)
      com.iqexception.fxhelper.api.rest.shop.GetQrCodesParamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.class, com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.Builder.class);
    }

    // Construct using com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      shopId_ = 0L;
      number_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesParam_descriptor;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam getDefaultInstanceForType() {
      return com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.getDefaultInstance();
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam build() {
      com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam buildPartial() {
      com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam result = new com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.shopId_ = shopId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.number_ = number_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam) {
        return mergeFrom((com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam other) {
      if (other == com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.getDefaultInstance()) return this;
      if (other.hasShopId()) {
        setShopId(other.getShopId());
      }
      if (other.hasNumber()) {
        setNumber(other.getNumber());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              shopId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              number_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long shopId_ ;
    /**
     * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
     * @return Whether the shopId field is set.
     */
    @java.lang.Override
    public boolean hasShopId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
     * @return The shopId.
     */
    @java.lang.Override
    public long getShopId() {
      return shopId_;
    }
    /**
     * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
     * @param value The shopId to set.
     * @return This builder for chaining.
     */
    public Builder setShopId(long value) {

      shopId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearShopId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      shopId_ = 0L;
      onChanged();
      return this;
    }

    private long number_ ;
    /**
     * <code>optional int64 number = 2 [(.buf.validate.field) = { ... }</code>
     * @return Whether the number field is set.
     */
    @java.lang.Override
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 number = 2 [(.buf.validate.field) = { ... }</code>
     * @return The number.
     */
    @java.lang.Override
    public long getNumber() {
      return number_;
    }
    /**
     * <code>optional int64 number = 2 [(.buf.validate.field) = { ... }</code>
     * @param value The number to set.
     * @return This builder for chaining.
     */
    public Builder setNumber(long value) {

      number_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 number = 2 [(.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      number_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam)
  }

  // @@protoc_insertion_point(class_scope:com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam)
  private static final com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam();
  }

  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetQrCodesParam>
      PARSER = new com.google.protobuf.AbstractParser<GetQrCodesParam>() {
    @java.lang.Override
    public GetQrCodesParam parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetQrCodesParam> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetQrCodesParam> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

