// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.shop;

public interface GetQrCodesResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.shop.GetQrCodesResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string qr_codes = 1;</code>
   * @return A list containing the qrCodes.
   */
  java.util.List<java.lang.String>
      getQrCodesList();
  /**
   * <code>repeated string qr_codes = 1;</code>
   * @return The count of qrCodes.
   */
  int getQrCodesCount();
  /**
   * <code>repeated string qr_codes = 1;</code>
   * @param index The index of the element to return.
   * @return The qrCodes at the given index.
   */
  java.lang.String getQrCodes(int index);
  /**
   * <code>repeated string qr_codes = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the qrCodes at the given index.
   */
  com.google.protobuf.ByteString
      getQrCodesBytes(int index);
}
