// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.shop;

/**
 * Protobuf type {@code com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest}
 */
public final class GetQrCodesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest)
    GetQrCodesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetQrCodesRequest.newBuilder() to construct.
  private GetQrCodesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetQrCodesRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetQrCodesRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest.class, com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int HEAD_FIELD_NUMBER = 1;
  private com.iqexception.fxhelper.api.common.MobileRequestHead head_;
  /**
   * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the head field is set.
   */
  @java.lang.Override
  public boolean hasHead() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
   * @return The head.
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.common.MobileRequestHead getHead() {
    return head_ == null ? com.iqexception.fxhelper.api.common.MobileRequestHead.getDefaultInstance() : head_;
  }
  /**
   * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.common.MobileRequestHeadOrBuilder getHeadOrBuilder() {
    return head_ == null ? com.iqexception.fxhelper.api.common.MobileRequestHead.getDefaultInstance() : head_;
  }

  public static final int PARAM_FIELD_NUMBER = 2;
  private com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param_;
  /**
   * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
   * @return Whether the param field is set.
   */
  @java.lang.Override
  public boolean hasParam() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
   * @return The param.
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam getParam() {
    return param_ == null ? com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.getDefaultInstance() : param_;
  }
  /**
   * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.rest.shop.GetQrCodesParamOrBuilder getParamOrBuilder() {
    return param_ == null ? com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.getDefaultInstance() : param_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getHead());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getParam());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHead());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getParam());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest)) {
      return super.equals(obj);
    }
    com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest other = (com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest) obj;

    if (hasHead() != other.hasHead()) return false;
    if (hasHead()) {
      if (!getHead()
          .equals(other.getHead())) return false;
    }
    if (hasParam() != other.hasParam()) return false;
    if (hasParam()) {
      if (!getParam()
          .equals(other.getParam())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHead()) {
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + getHead().hashCode();
    }
    if (hasParam()) {
      hash = (37 * hash) + PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getParam().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest)
      com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest.class, com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest.Builder.class);
    }

    // Construct using com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHeadFieldBuilder();
        getParamFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      head_ = null;
      if (headBuilder_ != null) {
        headBuilder_.dispose();
        headBuilder_ = null;
      }
      param_ = null;
      if (paramBuilder_ != null) {
        paramBuilder_.dispose();
        paramBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iqexception.fxhelper.api.rest.shop.ShopRest.internal_static_com_iqexception_fxhelper_api_rest_shop_GetQrCodesRequest_descriptor;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest getDefaultInstanceForType() {
      return com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest build() {
      com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest buildPartial() {
      com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest result = new com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.head_ = headBuilder_ == null
            ? head_
            : headBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.param_ = paramBuilder_ == null
            ? param_
            : paramBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest) {
        return mergeFrom((com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest other) {
      if (other == com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest.getDefaultInstance()) return this;
      if (other.hasHead()) {
        mergeHead(other.getHead());
      }
      if (other.hasParam()) {
        mergeParam(other.getParam());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHeadFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getParamFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.iqexception.fxhelper.api.common.MobileRequestHead head_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iqexception.fxhelper.api.common.MobileRequestHead, com.iqexception.fxhelper.api.common.MobileRequestHead.Builder, com.iqexception.fxhelper.api.common.MobileRequestHeadOrBuilder> headBuilder_;
    /**
     * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
     * @return Whether the head field is set.
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
     * @return The head.
     */
    public com.iqexception.fxhelper.api.common.MobileRequestHead getHead() {
      if (headBuilder_ == null) {
        return head_ == null ? com.iqexception.fxhelper.api.common.MobileRequestHead.getDefaultInstance() : head_;
      } else {
        return headBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
     */
    public Builder setHead(com.iqexception.fxhelper.api.common.MobileRequestHead value) {
      if (headBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        head_ = value;
      } else {
        headBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
     */
    public Builder setHead(
        com.iqexception.fxhelper.api.common.MobileRequestHead.Builder builderForValue) {
      if (headBuilder_ == null) {
        head_ = builderForValue.build();
      } else {
        headBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
     */
    public Builder mergeHead(com.iqexception.fxhelper.api.common.MobileRequestHead value) {
      if (headBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          head_ != null &&
          head_ != com.iqexception.fxhelper.api.common.MobileRequestHead.getDefaultInstance()) {
          getHeadBuilder().mergeFrom(value);
        } else {
          head_ = value;
        }
      } else {
        headBuilder_.mergeFrom(value);
      }
      if (head_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
     */
    public Builder clearHead() {
      bitField0_ = (bitField0_ & ~0x00000001);
      head_ = null;
      if (headBuilder_ != null) {
        headBuilder_.dispose();
        headBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
     */
    public com.iqexception.fxhelper.api.common.MobileRequestHead.Builder getHeadBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHeadFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
     */
    public com.iqexception.fxhelper.api.common.MobileRequestHeadOrBuilder getHeadOrBuilder() {
      if (headBuilder_ != null) {
        return headBuilder_.getMessageOrBuilder();
      } else {
        return head_ == null ?
            com.iqexception.fxhelper.api.common.MobileRequestHead.getDefaultInstance() : head_;
      }
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iqexception.fxhelper.api.common.MobileRequestHead, com.iqexception.fxhelper.api.common.MobileRequestHead.Builder, com.iqexception.fxhelper.api.common.MobileRequestHeadOrBuilder> 
        getHeadFieldBuilder() {
      if (headBuilder_ == null) {
        headBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.iqexception.fxhelper.api.common.MobileRequestHead, com.iqexception.fxhelper.api.common.MobileRequestHead.Builder, com.iqexception.fxhelper.api.common.MobileRequestHeadOrBuilder>(
                getHead(),
                getParentForChildren(),
                isClean());
        head_ = null;
      }
      return headBuilder_;
    }

    private com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam, com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.Builder, com.iqexception.fxhelper.api.rest.shop.GetQrCodesParamOrBuilder> paramBuilder_;
    /**
     * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
     * @return Whether the param field is set.
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
     * @return The param.
     */
    public com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam getParam() {
      if (paramBuilder_ == null) {
        return param_ == null ? com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.getDefaultInstance() : param_;
      } else {
        return paramBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
     */
    public Builder setParam(com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam value) {
      if (paramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        param_ = value;
      } else {
        paramBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
     */
    public Builder setParam(
        com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.Builder builderForValue) {
      if (paramBuilder_ == null) {
        param_ = builderForValue.build();
      } else {
        paramBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
     */
    public Builder mergeParam(com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam value) {
      if (paramBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          param_ != null &&
          param_ != com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.getDefaultInstance()) {
          getParamBuilder().mergeFrom(value);
        } else {
          param_ = value;
        }
      } else {
        paramBuilder_.mergeFrom(value);
      }
      if (param_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
     */
    public Builder clearParam() {
      bitField0_ = (bitField0_ & ~0x00000002);
      param_ = null;
      if (paramBuilder_ != null) {
        paramBuilder_.dispose();
        paramBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
     */
    public com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.Builder getParamBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getParamFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
     */
    public com.iqexception.fxhelper.api.rest.shop.GetQrCodesParamOrBuilder getParamOrBuilder() {
      if (paramBuilder_ != null) {
        return paramBuilder_.getMessageOrBuilder();
      } else {
        return param_ == null ?
            com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.getDefaultInstance() : param_;
      }
    }
    /**
     * <code>.com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam param = 2 [(.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam, com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.Builder, com.iqexception.fxhelper.api.rest.shop.GetQrCodesParamOrBuilder> 
        getParamFieldBuilder() {
      if (paramBuilder_ == null) {
        paramBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam, com.iqexception.fxhelper.api.rest.shop.GetQrCodesParam.Builder, com.iqexception.fxhelper.api.rest.shop.GetQrCodesParamOrBuilder>(
                getParam(),
                getParentForChildren(),
                isClean());
        param_ = null;
      }
      return paramBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest)
  }

  // @@protoc_insertion_point(class_scope:com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest)
  private static final com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest();
  }

  public static com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetQrCodesRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetQrCodesRequest>() {
    @java.lang.Override
    public GetQrCodesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetQrCodesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetQrCodesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iqexception.fxhelper.api.rest.shop.GetQrCodesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

