// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.shop;

public interface GetShopDetailInfoParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.shop.GetShopDetailInfoParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the shopId field is set.
   */
  boolean hasShopId();
  /**
   * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return The shopId.
   */
  long getShopId();
}
