// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.shop;

public interface UpdateParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.shop.UpdateParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the shopId field is set.
   */
  boolean hasShopId();
  /**
   * <code>optional int64 shop_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return The shopId.
   */
  long getShopId();

  /**
   * <code>optional string name = 2 [(.buf.validate.field) = { ... }</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2 [(.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string logo = 3 [(.buf.validate.field) = { ... }</code>
   * @return Whether the logo field is set.
   */
  boolean hasLogo();
  /**
   * <code>optional string logo = 3 [(.buf.validate.field) = { ... }</code>
   * @return The logo.
   */
  java.lang.String getLogo();
  /**
   * <code>optional string logo = 3 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for logo.
   */
  com.google.protobuf.ByteString
      getLogoBytes();

  /**
   * <code>optional string intro = 4 [(.buf.validate.field) = { ... }</code>
   * @return Whether the intro field is set.
   */
  boolean hasIntro();
  /**
   * <code>optional string intro = 4 [(.buf.validate.field) = { ... }</code>
   * @return The intro.
   */
  java.lang.String getIntro();
  /**
   * <code>optional string intro = 4 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for intro.
   */
  com.google.protobuf.ByteString
      getIntroBytes();

  /**
   * <code>optional string address = 5 [(.buf.validate.field) = { ... }</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 5 [(.buf.validate.field) = { ... }</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 5 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>optional string phone = 6 [(.buf.validate.field) = { ... }</code>
   * @return Whether the phone field is set.
   */
  boolean hasPhone();
  /**
   * <code>optional string phone = 6 [(.buf.validate.field) = { ... }</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>optional string phone = 6 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
