// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.agg;

public final class AggRest {
  private AggRest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_ShopOrderInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_ShopOrderInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iqexception_fxhelper_api_rest_agg_UserOrderInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iqexception_fxhelper_api_rest_agg_UserOrderInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016agg.rest.proto\022%com.iqexception.fxhelp" +
      "er.api.rest.agg\032\014common.proto\032\037google/pr" +
      "otobuf/timestamp.proto\032\033buf/validate/val" +
      "idate.proto\"\252\001\n\016GetShopRequest\022L\n\004head\030\001" +
      " \001(\01326.com.iqexception.fxhelper.api.comm" +
      "on.MobileRequestHeadB\006\272H\003\310\001\001\022J\n\005param\030\002 " +
      "\001(\01323.com.iqexception.fxhelper.api.rest." +
      "agg.GetShopParamB\006\272H\003\310\001\001\"<\n\014GetShopParam" +
      "\022 \n\007shop_id\030\001 \001(\003B\n\272H\007\"\002 \000\310\001\001H\000\210\001\001B\n\n\010_s" +
      "hop_id\"\234\001\n\017GetShopResponse\022C\n\006status\030\001 \001" +
      "(\01323.com.iqexception.fxhelper.api.common" +
      ".ResponseStatus\022D\n\006result\030\002 \001(\01324.com.iq" +
      "exception.fxhelper.api.rest.agg.GetShopR" +
      "esult\"\253\004\n\rGetShopResult\022\024\n\007shop_id\030\001 \001(\003" +
      "H\000\210\001\001\022\032\n\rowner_user_id\030\002 \001(\003H\001\210\001\001\022\026\n\tsho" +
      "p_name\030\003 \001(\tH\002\210\001\001\022\021\n\004logo\030\004 \001(\tH\003\210\001\001\022\022\n\005" +
      "intro\030\005 \001(\tH\004\210\001\001\022\024\n\007address\030\006 \001(\tH\005\210\001\001\022\022" +
      "\n\005phone\030\007 \001(\tH\006\210\001\001\022\023\n\006status\030\010 \001(\005H\007\210\001\001\022" +
      "3\n\ncreated_at\030\t \001(\0132\032.google.protobuf.Ti" +
      "mestampH\010\210\001\001\0223\n\nupdated_at\030\n \001(\0132\032.googl" +
      "e.protobuf.TimestampH\t\210\001\001\022\024\n\007balance\030\013 \001" +
      "(\tH\n\210\001\001\022\030\n\013order_count\030\014 \001(\005H\013\210\001\001\022\037\n\022ord" +
      "er_total_amount\030\r \001(\tH\014\210\001\001B\n\n\010_shop_idB\020" +
      "\n\016_owner_user_idB\014\n\n_shop_nameB\007\n\005_logoB" +
      "\010\n\006_introB\n\n\010_addressB\010\n\006_phoneB\t\n\007_stat" +
      "usB\r\n\013_created_atB\r\n\013_updated_atB\n\n\010_bal" +
      "anceB\016\n\014_order_countB\025\n\023_order_total_amo" +
      "unt\"\274\001\n\027GetShopOrderListRequest\022L\n\004head\030" +
      "\001 \001(\01326.com.iqexception.fxhelper.api.com" +
      "mon.MobileRequestHeadB\006\272H\003\310\001\001\022S\n\005param\030\002" +
      " \001(\0132<.com.iqexception.fxhelper.api.rest" +
      ".agg.GetShopOrderListParamB\006\272H\003\310\001\001\"\243\002\n\025G" +
      "etShopOrderListParam\022 \n\007shop_id\030\001 \001(\003B\n\272" +
      "H\007\"\002 \000\310\001\001H\000\210\001\001\022\023\n\006status\030\002 \001(\005H\001\210\001\001\022-\n\004f" +
      "rom\030\003 \001(\0132\032.google.protobuf.TimestampH\002\210" +
      "\001\001\022+\n\002to\030\004 \001(\0132\032.google.protobuf.Timesta" +
      "mpH\003\210\001\001\022\034\n\006offset\030\005 \001(\005B\007\272H\004\032\002(\000H\004\210\001\001\022\035\n" +
      "\005limit\030\006 \001(\005B\t\272H\006\032\004\030\024 \000H\005\210\001\001B\n\n\010_shop_id" +
      "B\t\n\007_statusB\007\n\005_fromB\005\n\003_toB\t\n\007_offsetB\010" +
      "\n\006_limit\"\256\001\n\030GetShopOrderListResponse\022C\n" +
      "\006status\030\001 \001(\01323.com.iqexception.fxhelper" +
      ".api.common.ResponseStatus\022M\n\006result\030\002 \001" +
      "(\0132=.com.iqexception.fxhelper.api.rest.a" +
      "gg.GetShopOrderListResult\"c\n\026GetShopOrde" +
      "rListResult\022I\n\013order_infos\030\001 \003(\01324.com.i" +
      "qexception.fxhelper.api.rest.agg.ShopOrd" +
      "erInfo\"\375\003\n\rShopOrderInfo\022\017\n\002id\030\001 \001(\003H\000\210\001" +
      "\001\022\024\n\007shop_id\030\002 \001(\003H\001\210\001\001\022\024\n\007user_id\030\003 \001(\003" +
      "H\002\210\001\001\022\024\n\007capture\030\004 \001(\tH\003\210\001\001\022\023\n\006amount\030\005 " +
      "\001(\tH\004\210\001\001\0220\n\007fx_time\030\006 \001(\0132\032.google.proto" +
      "buf.TimestampH\005\210\001\001\022\023\n\006status\030\007 \001(\005H\006\210\001\001\022" +
      "\025\n\010fail_msg\030\010 \001(\tH\007\210\001\001\0223\n\ncreated_at\030\t \001" +
      "(\0132\032.google.protobuf.TimestampH\010\210\001\001\0223\n\nu" +
      "pdated_at\030\n \001(\0132\032.google.protobuf.Timest" +
      "ampH\t\210\001\001\022\026\n\tnick_name\030\013 \001(\tH\n\210\001\001\022\023\n\006avat" +
      "ar\030\014 \001(\tH\013\210\001\001B\005\n\003_idB\n\n\010_shop_idB\n\n\010_use" +
      "r_idB\n\n\010_captureB\t\n\007_amountB\n\n\010_fx_timeB" +
      "\t\n\007_statusB\013\n\t_fail_msgB\r\n\013_created_atB\r" +
      "\n\013_updated_atB\014\n\n_nick_nameB\t\n\007_avatar\"\274" +
      "\001\n\027GetUserOrderListRequest\022L\n\004head\030\001 \001(\013" +
      "26.com.iqexception.fxhelper.api.common.M" +
      "obileRequestHeadB\006\272H\003\310\001\001\022S\n\005param\030\002 \001(\0132" +
      "<.com.iqexception.fxhelper.api.rest.agg." +
      "GetUserOrderListParamB\006\272H\003\310\001\001\"\365\001\n\025GetUse" +
      "rOrderListParam\022\023\n\006status\030\001 \001(\005H\000\210\001\001\022-\n\004" +
      "from\030\002 \001(\0132\032.google.protobuf.TimestampH\001" +
      "\210\001\001\022+\n\002to\030\003 \001(\0132\032.google.protobuf.Timest" +
      "ampH\002\210\001\001\022\034\n\006offset\030\004 \001(\005B\007\272H\004\032\002(\000H\003\210\001\001\022\035" +
      "\n\005limit\030\005 \001(\005B\t\272H\006\032\004\030\024 \000H\004\210\001\001B\t\n\007_status" +
      "B\007\n\005_fromB\005\n\003_toB\t\n\007_offsetB\010\n\006_limit\"\256\001" +
      "\n\030GetUserOrderListResponse\022C\n\006status\030\001 \001" +
      "(\01323.com.iqexception.fxhelper.api.common" +
      ".ResponseStatus\022M\n\006result\030\002 \001(\0132=.com.iq" +
      "exception.fxhelper.api.rest.agg.GetUserO" +
      "rderListResult\"c\n\026GetUserOrderListResult" +
      "\022I\n\013order_infos\030\001 \003(\01324.com.iqexception." +
      "fxhelper.api.rest.agg.UserOrderInfo\"\203\004\n\r" +
      "UserOrderInfo\022\017\n\002id\030\001 \001(\003H\000\210\001\001\022\024\n\007shop_i" +
      "d\030\002 \001(\003H\001\210\001\001\022\024\n\007user_id\030\003 \001(\003H\002\210\001\001\022\024\n\007ca" +
      "pture\030\004 \001(\tH\003\210\001\001\022\023\n\006amount\030\005 \001(\tH\004\210\001\001\0220\n" +
      "\007fx_time\030\006 \001(\0132\032.google.protobuf.Timesta" +
      "mpH\005\210\001\001\022\023\n\006status\030\007 \001(\005H\006\210\001\001\022\025\n\010fail_msg" +
      "\030\010 \001(\tH\007\210\001\001\0223\n\ncreated_at\030\t \001(\0132\032.google" +
      ".protobuf.TimestampH\010\210\001\001\0223\n\nupdated_at\030\n" +
      " \001(\0132\032.google.protobuf.TimestampH\t\210\001\001\022\026\n" +
      "\tshop_name\030\013 \001(\tH\n\210\001\001\022\026\n\tshop_logo\030\014 \001(\t" +
      "H\013\210\001\001B\005\n\003_idB\n\n\010_shop_idB\n\n\010_user_idB\n\n\010" +
      "_captureB\t\n\007_amountB\n\n\010_fx_timeB\t\n\007_stat" +
      "usB\013\n\t_fail_msgB\r\n\013_created_atB\r\n\013_updat" +
      "ed_atB\014\n\n_shop_nameB\014\n\n_shop_logo2\266\003\n\016Ag" +
      "gRestService\022x\n\007getShop\0225.com.iqexceptio" +
      "n.fxhelper.api.rest.agg.GetShopRequest\0326" +
      ".com.iqexception.fxhelper.api.rest.agg.G" +
      "etShopResponse\022\223\001\n\020getShopOrderList\022>.co" +
      "m.iqexception.fxhelper.api.rest.agg.GetS" +
      "hopOrderListRequest\032?.com.iqexception.fx" +
      "helper.api.rest.agg.GetShopOrderListResp" +
      "onse\022\223\001\n\020getUserOrderList\022>.com.iqexcept" +
      "ion.fxhelper.api.rest.agg.GetUserOrderLi" +
      "stRequest\032?.com.iqexception.fxhelper.api" +
      ".rest.agg.GetUserOrderListResponseB\002P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.iqexception.fxhelper.api.common.Common.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopRequest_descriptor,
        new java.lang.String[] { "Head", "Param", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopParam_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopParam_descriptor,
        new java.lang.String[] { "ShopId", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResponse_descriptor,
        new java.lang.String[] { "Status", "Result", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopResult_descriptor,
        new java.lang.String[] { "ShopId", "OwnerUserId", "ShopName", "Logo", "Intro", "Address", "Phone", "Status", "CreatedAt", "UpdatedAt", "Balance", "OrderCount", "OrderTotalAmount", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListRequest_descriptor,
        new java.lang.String[] { "Head", "Param", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListParam_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListParam_descriptor,
        new java.lang.String[] { "ShopId", "Status", "From", "To", "Offset", "Limit", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResponse_descriptor,
        new java.lang.String[] { "Status", "Result", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_descriptor,
        new java.lang.String[] { "OrderInfos", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_ShopOrderInfo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_iqexception_fxhelper_api_rest_agg_ShopOrderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_ShopOrderInfo_descriptor,
        new java.lang.String[] { "Id", "ShopId", "UserId", "Capture", "Amount", "FxTime", "Status", "FailMsg", "CreatedAt", "UpdatedAt", "NickName", "Avatar", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListRequest_descriptor,
        new java.lang.String[] { "Head", "Param", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListParam_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListParam_descriptor,
        new java.lang.String[] { "Status", "From", "To", "Offset", "Limit", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResponse_descriptor,
        new java.lang.String[] { "Status", "Result", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResult_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_GetUserOrderListResult_descriptor,
        new java.lang.String[] { "OrderInfos", });
    internal_static_com_iqexception_fxhelper_api_rest_agg_UserOrderInfo_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_iqexception_fxhelper_api_rest_agg_UserOrderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iqexception_fxhelper_api_rest_agg_UserOrderInfo_descriptor,
        new java.lang.String[] { "Id", "ShopId", "UserId", "Capture", "Amount", "FxTime", "Status", "FailMsg", "CreatedAt", "UpdatedAt", "ShopName", "ShopLogo", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.iqexception.fxhelper.api.common.Common.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
