// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.agg;

public interface GetShopRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.agg.GetShopRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the head field is set.
   */
  boolean hasHead();
  /**
   * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
   * @return The head.
   */
  com.iqexception.fxhelper.api.common.MobileRequestHead getHead();
  /**
   * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
   */
  com.iqexception.fxhelper.api.common.MobileRequestHeadOrBuilder getHeadOrBuilder();

  /**
   * <code>.com.iqexception.fxhelper.api.rest.agg.GetShopParam param = 2 [(.buf.validate.field) = { ... }</code>
   * @return Whether the param field is set.
   */
  boolean hasParam();
  /**
   * <code>.com.iqexception.fxhelper.api.rest.agg.GetShopParam param = 2 [(.buf.validate.field) = { ... }</code>
   * @return The param.
   */
  com.iqexception.fxhelper.api.rest.agg.GetShopParam getParam();
  /**
   * <code>.com.iqexception.fxhelper.api.rest.agg.GetShopParam param = 2 [(.buf.validate.field) = { ... }</code>
   */
  com.iqexception.fxhelper.api.rest.agg.GetShopParamOrBuilder getParamOrBuilder();
}
