// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.agg;

public interface GetShopOrderListResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  java.util.List<com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo> 
      getOrderInfosList();
  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo getOrderInfos(int index);
  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  int getOrderInfosCount();
  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  java.util.List<? extends com.iqexception.fxhelper.api.rest.agg.ShopOrderInfoOrBuilder> 
      getOrderInfosOrBuilderList();
  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  com.iqexception.fxhelper.api.rest.agg.ShopOrderInfoOrBuilder getOrderInfosOrBuilder(
      int index);
}
