// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.agg;

/**
 * Protobuf type {@code com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult}
 */
public final class GetShopOrderListResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult)
    GetShopOrderListResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetShopOrderListResult.newBuilder() to construct.
  private GetShopOrderListResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetShopOrderListResult() {
    orderInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetShopOrderListResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iqexception.fxhelper.api.rest.agg.AggRest.internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iqexception.fxhelper.api.rest.agg.AggRest.internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult.class, com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult.Builder.class);
  }

  public static final int ORDER_INFOS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo> orderInfos_;
  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo> getOrderInfosList() {
    return orderInfos_;
  }
  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.iqexception.fxhelper.api.rest.agg.ShopOrderInfoOrBuilder> 
      getOrderInfosOrBuilderList() {
    return orderInfos_;
  }
  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  @java.lang.Override
  public int getOrderInfosCount() {
    return orderInfos_.size();
  }
  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo getOrderInfos(int index) {
    return orderInfos_.get(index);
  }
  /**
   * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.rest.agg.ShopOrderInfoOrBuilder getOrderInfosOrBuilder(
      int index) {
    return orderInfos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < orderInfos_.size(); i++) {
      output.writeMessage(1, orderInfos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < orderInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, orderInfos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult)) {
      return super.equals(obj);
    }
    com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult other = (com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult) obj;

    if (!getOrderInfosList()
        .equals(other.getOrderInfosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOrderInfosCount() > 0) {
      hash = (37 * hash) + ORDER_INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getOrderInfosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult)
      com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iqexception.fxhelper.api.rest.agg.AggRest.internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iqexception.fxhelper.api.rest.agg.AggRest.internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult.class, com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult.Builder.class);
    }

    // Construct using com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (orderInfosBuilder_ == null) {
        orderInfos_ = java.util.Collections.emptyList();
      } else {
        orderInfos_ = null;
        orderInfosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iqexception.fxhelper.api.rest.agg.AggRest.internal_static_com_iqexception_fxhelper_api_rest_agg_GetShopOrderListResult_descriptor;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult getDefaultInstanceForType() {
      return com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult build() {
      com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult buildPartial() {
      com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult result = new com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult result) {
      if (orderInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          orderInfos_ = java.util.Collections.unmodifiableList(orderInfos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.orderInfos_ = orderInfos_;
      } else {
        result.orderInfos_ = orderInfosBuilder_.build();
      }
    }

    private void buildPartial0(com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult) {
        return mergeFrom((com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult other) {
      if (other == com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult.getDefaultInstance()) return this;
      if (orderInfosBuilder_ == null) {
        if (!other.orderInfos_.isEmpty()) {
          if (orderInfos_.isEmpty()) {
            orderInfos_ = other.orderInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOrderInfosIsMutable();
            orderInfos_.addAll(other.orderInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.orderInfos_.isEmpty()) {
          if (orderInfosBuilder_.isEmpty()) {
            orderInfosBuilder_.dispose();
            orderInfosBuilder_ = null;
            orderInfos_ = other.orderInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            orderInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderInfosFieldBuilder() : null;
          } else {
            orderInfosBuilder_.addAllMessages(other.orderInfos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo m =
                  input.readMessage(
                      com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.parser(),
                      extensionRegistry);
              if (orderInfosBuilder_ == null) {
                ensureOrderInfosIsMutable();
                orderInfos_.add(m);
              } else {
                orderInfosBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo> orderInfos_ =
      java.util.Collections.emptyList();
    private void ensureOrderInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        orderInfos_ = new java.util.ArrayList<com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo>(orderInfos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfoOrBuilder> orderInfosBuilder_;

    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public java.util.List<com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo> getOrderInfosList() {
      if (orderInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderInfos_);
      } else {
        return orderInfosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public int getOrderInfosCount() {
      if (orderInfosBuilder_ == null) {
        return orderInfos_.size();
      } else {
        return orderInfosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo getOrderInfos(int index) {
      if (orderInfosBuilder_ == null) {
        return orderInfos_.get(index);
      } else {
        return orderInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public Builder setOrderInfos(
        int index, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo value) {
      if (orderInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderInfosIsMutable();
        orderInfos_.set(index, value);
        onChanged();
      } else {
        orderInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public Builder setOrderInfos(
        int index, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder builderForValue) {
      if (orderInfosBuilder_ == null) {
        ensureOrderInfosIsMutable();
        orderInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public Builder addOrderInfos(com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo value) {
      if (orderInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderInfosIsMutable();
        orderInfos_.add(value);
        onChanged();
      } else {
        orderInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public Builder addOrderInfos(
        int index, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo value) {
      if (orderInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderInfosIsMutable();
        orderInfos_.add(index, value);
        onChanged();
      } else {
        orderInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public Builder addOrderInfos(
        com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder builderForValue) {
      if (orderInfosBuilder_ == null) {
        ensureOrderInfosIsMutable();
        orderInfos_.add(builderForValue.build());
        onChanged();
      } else {
        orderInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public Builder addOrderInfos(
        int index, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder builderForValue) {
      if (orderInfosBuilder_ == null) {
        ensureOrderInfosIsMutable();
        orderInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public Builder addAllOrderInfos(
        java.lang.Iterable<? extends com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo> values) {
      if (orderInfosBuilder_ == null) {
        ensureOrderInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderInfos_);
        onChanged();
      } else {
        orderInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public Builder clearOrderInfos() {
      if (orderInfosBuilder_ == null) {
        orderInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        orderInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public Builder removeOrderInfos(int index) {
      if (orderInfosBuilder_ == null) {
        ensureOrderInfosIsMutable();
        orderInfos_.remove(index);
        onChanged();
      } else {
        orderInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder getOrderInfosBuilder(
        int index) {
      return getOrderInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.rest.agg.ShopOrderInfoOrBuilder getOrderInfosOrBuilder(
        int index) {
      if (orderInfosBuilder_ == null) {
        return orderInfos_.get(index);  } else {
        return orderInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public java.util.List<? extends com.iqexception.fxhelper.api.rest.agg.ShopOrderInfoOrBuilder> 
         getOrderInfosOrBuilderList() {
      if (orderInfosBuilder_ != null) {
        return orderInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderInfos_);
      }
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder addOrderInfosBuilder() {
      return getOrderInfosFieldBuilder().addBuilder(
          com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder addOrderInfosBuilder(
        int index) {
      return getOrderInfosFieldBuilder().addBuilder(
          index, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo order_infos = 1;</code>
     */
    public java.util.List<com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder> 
         getOrderInfosBuilderList() {
      return getOrderInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfoOrBuilder> 
        getOrderInfosFieldBuilder() {
      if (orderInfosBuilder_ == null) {
        orderInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo.Builder, com.iqexception.fxhelper.api.rest.agg.ShopOrderInfoOrBuilder>(
                orderInfos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        orderInfos_ = null;
      }
      return orderInfosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult)
  }

  // @@protoc_insertion_point(class_scope:com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult)
  private static final com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult();
  }

  public static com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetShopOrderListResult>
      PARSER = new com.google.protobuf.AbstractParser<GetShopOrderListResult>() {
    @java.lang.Override
    public GetShopOrderListResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetShopOrderListResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetShopOrderListResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iqexception.fxhelper.api.rest.agg.GetShopOrderListResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

