// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.agg;

public interface GetUserOrderListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.agg.GetUserOrderListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   * @return The status.
   */
  com.iqexception.fxhelper.api.common.ResponseStatus getStatus();
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   */
  com.iqexception.fxhelper.api.common.ResponseStatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.com.iqexception.fxhelper.api.rest.agg.GetUserOrderListResult result = 2;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.com.iqexception.fxhelper.api.rest.agg.GetUserOrderListResult result = 2;</code>
   * @return The result.
   */
  com.iqexception.fxhelper.api.rest.agg.GetUserOrderListResult getResult();
  /**
   * <code>.com.iqexception.fxhelper.api.rest.agg.GetUserOrderListResult result = 2;</code>
   */
  com.iqexception.fxhelper.api.rest.agg.GetUserOrderListResultOrBuilder getResultOrBuilder();
}
