// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.agg;

public interface ShopOrderInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.agg.ShopOrderInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional int64 shop_id = 2;</code>
   * @return Whether the shopId field is set.
   */
  boolean hasShopId();
  /**
   * <code>optional int64 shop_id = 2;</code>
   * @return The shopId.
   */
  long getShopId();

  /**
   * <code>optional int64 user_id = 3;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional int64 user_id = 3;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>optional string capture = 4;</code>
   * @return Whether the capture field is set.
   */
  boolean hasCapture();
  /**
   * <code>optional string capture = 4;</code>
   * @return The capture.
   */
  java.lang.String getCapture();
  /**
   * <code>optional string capture = 4;</code>
   * @return The bytes for capture.
   */
  com.google.protobuf.ByteString
      getCaptureBytes();

  /**
   * <code>optional string amount = 5;</code>
   * @return Whether the amount field is set.
   */
  boolean hasAmount();
  /**
   * <code>optional string amount = 5;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>optional string amount = 5;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>optional .google.protobuf.Timestamp fx_time = 6;</code>
   * @return Whether the fxTime field is set.
   */
  boolean hasFxTime();
  /**
   * <code>optional .google.protobuf.Timestamp fx_time = 6;</code>
   * @return The fxTime.
   */
  com.google.protobuf.Timestamp getFxTime();
  /**
   * <code>optional .google.protobuf.Timestamp fx_time = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getFxTimeOrBuilder();

  /**
   * <code>optional int32 status = 7;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>optional int32 status = 7;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>optional string fail_msg = 8;</code>
   * @return Whether the failMsg field is set.
   */
  boolean hasFailMsg();
  /**
   * <code>optional string fail_msg = 8;</code>
   * @return The failMsg.
   */
  java.lang.String getFailMsg();
  /**
   * <code>optional string fail_msg = 8;</code>
   * @return The bytes for failMsg.
   */
  com.google.protobuf.ByteString
      getFailMsgBytes();

  /**
   * <code>optional .google.protobuf.Timestamp created_at = 9;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp created_at = 9;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp created_at = 9;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>optional .google.protobuf.Timestamp updated_at = 10;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp updated_at = 10;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp updated_at = 10;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>optional string nick_name = 11;</code>
   * @return Whether the nickName field is set.
   */
  boolean hasNickName();
  /**
   * <code>optional string nick_name = 11;</code>
   * @return The nickName.
   */
  java.lang.String getNickName();
  /**
   * <code>optional string nick_name = 11;</code>
   * @return The bytes for nickName.
   */
  com.google.protobuf.ByteString
      getNickNameBytes();

  /**
   * <code>optional string avatar = 12;</code>
   * @return Whether the avatar field is set.
   */
  boolean hasAvatar();
  /**
   * <code>optional string avatar = 12;</code>
   * @return The avatar.
   */
  java.lang.String getAvatar();
  /**
   * <code>optional string avatar = 12;</code>
   * @return The bytes for avatar.
   */
  com.google.protobuf.ByteString
      getAvatarBytes();
}
