// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.user;

public interface CheckLoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.user.CheckLoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   * @return The status.
   */
  com.iqexception.fxhelper.api.common.ResponseStatus getStatus();
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   */
  com.iqexception.fxhelper.api.common.ResponseStatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.com.iqexception.fxhelper.api.user.CheckLoginResult result = 2;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.com.iqexception.fxhelper.api.user.CheckLoginResult result = 2;</code>
   * @return The result.
   */
  com.iqexception.fxhelper.api.user.CheckLoginResult getResult();
  /**
   * <code>.com.iqexception.fxhelper.api.user.CheckLoginResult result = 2;</code>
   */
  com.iqexception.fxhelper.api.user.CheckLoginResultOrBuilder getResultOrBuilder();
}
