// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.user;

public interface GetUserListResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.user.GetUserListResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.iqexception.fxhelper.api.user.UserInfo user_infos = 1;</code>
   */
  java.util.List<com.iqexception.fxhelper.api.user.UserInfo> 
      getUserInfosList();
  /**
   * <code>repeated .com.iqexception.fxhelper.api.user.UserInfo user_infos = 1;</code>
   */
  com.iqexception.fxhelper.api.user.UserInfo getUserInfos(int index);
  /**
   * <code>repeated .com.iqexception.fxhelper.api.user.UserInfo user_infos = 1;</code>
   */
  int getUserInfosCount();
  /**
   * <code>repeated .com.iqexception.fxhelper.api.user.UserInfo user_infos = 1;</code>
   */
  java.util.List<? extends com.iqexception.fxhelper.api.user.UserInfoOrBuilder> 
      getUserInfosOrBuilderList();
  /**
   * <code>repeated .com.iqexception.fxhelper.api.user.UserInfo user_infos = 1;</code>
   */
  com.iqexception.fxhelper.api.user.UserInfoOrBuilder getUserInfosOrBuilder(
      int index);
}
