// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.user;

public interface GetUserListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.user.GetUserListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 user_ids = 1 [(.buf.validate.field) = { ... }</code>
   * @return A list containing the userIds.
   */
  java.util.List<java.lang.Long> getUserIdsList();
  /**
   * <code>repeated int64 user_ids = 1 [(.buf.validate.field) = { ... }</code>
   * @return The count of userIds.
   */
  int getUserIdsCount();
  /**
   * <code>repeated int64 user_ids = 1 [(.buf.validate.field) = { ... }</code>
   * @param index The index of the element to return.
   * @return The userIds at the given index.
   */
  long getUserIds(int index);
}
