// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: misc.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.misc;

/**
 * Protobuf type {@code com.iqexception.fxhelper.api.misc.GetAccessTokenResponse}
 */
public final class GetAccessTokenResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iqexception.fxhelper.api.misc.GetAccessTokenResponse)
    GetAccessTokenResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAccessTokenResponse.newBuilder() to construct.
  private GetAccessTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAccessTokenResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAccessTokenResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_GetAccessTokenResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_GetAccessTokenResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iqexception.fxhelper.api.misc.GetAccessTokenResponse.class, com.iqexception.fxhelper.api.misc.GetAccessTokenResponse.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private com.iqexception.fxhelper.api.common.ResponseStatus status_;
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.common.ResponseStatus getStatus() {
    return status_ == null ? com.iqexception.fxhelper.api.common.ResponseStatus.getDefaultInstance() : status_;
  }
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.common.ResponseStatusOrBuilder getStatusOrBuilder() {
    return status_ == null ? com.iqexception.fxhelper.api.common.ResponseStatus.getDefaultInstance() : status_;
  }

  public static final int RESULT_FIELD_NUMBER = 2;
  private com.iqexception.fxhelper.api.misc.GetAccessTokenResult result_;
  /**
   * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
   * @return Whether the result field is set.
   */
  @java.lang.Override
  public boolean hasResult() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
   * @return The result.
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.misc.GetAccessTokenResult getResult() {
    return result_ == null ? com.iqexception.fxhelper.api.misc.GetAccessTokenResult.getDefaultInstance() : result_;
  }
  /**
   * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
   */
  @java.lang.Override
  public com.iqexception.fxhelper.api.misc.GetAccessTokenResultOrBuilder getResultOrBuilder() {
    return result_ == null ? com.iqexception.fxhelper.api.misc.GetAccessTokenResult.getDefaultInstance() : result_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getStatus());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getResult());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResult());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iqexception.fxhelper.api.misc.GetAccessTokenResponse)) {
      return super.equals(obj);
    }
    com.iqexception.fxhelper.api.misc.GetAccessTokenResponse other = (com.iqexception.fxhelper.api.misc.GetAccessTokenResponse) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasResult() != other.hasResult()) return false;
    if (hasResult()) {
      if (!getResult()
          .equals(other.getResult())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasResult()) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iqexception.fxhelper.api.misc.GetAccessTokenResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iqexception.fxhelper.api.misc.GetAccessTokenResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iqexception.fxhelper.api.misc.GetAccessTokenResponse)
      com.iqexception.fxhelper.api.misc.GetAccessTokenResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_GetAccessTokenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_GetAccessTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iqexception.fxhelper.api.misc.GetAccessTokenResponse.class, com.iqexception.fxhelper.api.misc.GetAccessTokenResponse.Builder.class);
    }

    // Construct using com.iqexception.fxhelper.api.misc.GetAccessTokenResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStatusFieldBuilder();
        getResultFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      result_ = null;
      if (resultBuilder_ != null) {
        resultBuilder_.dispose();
        resultBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_GetAccessTokenResponse_descriptor;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.misc.GetAccessTokenResponse getDefaultInstanceForType() {
      return com.iqexception.fxhelper.api.misc.GetAccessTokenResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.misc.GetAccessTokenResponse build() {
      com.iqexception.fxhelper.api.misc.GetAccessTokenResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.misc.GetAccessTokenResponse buildPartial() {
      com.iqexception.fxhelper.api.misc.GetAccessTokenResponse result = new com.iqexception.fxhelper.api.misc.GetAccessTokenResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.iqexception.fxhelper.api.misc.GetAccessTokenResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = statusBuilder_ == null
            ? status_
            : statusBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.result_ = resultBuilder_ == null
            ? result_
            : resultBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iqexception.fxhelper.api.misc.GetAccessTokenResponse) {
        return mergeFrom((com.iqexception.fxhelper.api.misc.GetAccessTokenResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iqexception.fxhelper.api.misc.GetAccessTokenResponse other) {
      if (other == com.iqexception.fxhelper.api.misc.GetAccessTokenResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasResult()) {
        mergeResult(other.getResult());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.iqexception.fxhelper.api.common.ResponseStatus status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iqexception.fxhelper.api.common.ResponseStatus, com.iqexception.fxhelper.api.common.ResponseStatus.Builder, com.iqexception.fxhelper.api.common.ResponseStatusOrBuilder> statusBuilder_;
    /**
     * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
     * @return The status.
     */
    public com.iqexception.fxhelper.api.common.ResponseStatus getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.iqexception.fxhelper.api.common.ResponseStatus.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
     */
    public Builder setStatus(com.iqexception.fxhelper.api.common.ResponseStatus value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
      } else {
        statusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
     */
    public Builder setStatus(
        com.iqexception.fxhelper.api.common.ResponseStatus.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
     */
    public Builder mergeStatus(com.iqexception.fxhelper.api.common.ResponseStatus value) {
      if (statusBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          status_ != null &&
          status_ != com.iqexception.fxhelper.api.common.ResponseStatus.getDefaultInstance()) {
          getStatusBuilder().mergeFrom(value);
        } else {
          status_ = value;
        }
      } else {
        statusBuilder_.mergeFrom(value);
      }
      if (status_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
     */
    public com.iqexception.fxhelper.api.common.ResponseStatus.Builder getStatusBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
     */
    public com.iqexception.fxhelper.api.common.ResponseStatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.iqexception.fxhelper.api.common.ResponseStatus.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iqexception.fxhelper.api.common.ResponseStatus, com.iqexception.fxhelper.api.common.ResponseStatus.Builder, com.iqexception.fxhelper.api.common.ResponseStatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.iqexception.fxhelper.api.common.ResponseStatus, com.iqexception.fxhelper.api.common.ResponseStatus.Builder, com.iqexception.fxhelper.api.common.ResponseStatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private com.iqexception.fxhelper.api.misc.GetAccessTokenResult result_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iqexception.fxhelper.api.misc.GetAccessTokenResult, com.iqexception.fxhelper.api.misc.GetAccessTokenResult.Builder, com.iqexception.fxhelper.api.misc.GetAccessTokenResultOrBuilder> resultBuilder_;
    /**
     * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
     * @return Whether the result field is set.
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
     * @return The result.
     */
    public com.iqexception.fxhelper.api.misc.GetAccessTokenResult getResult() {
      if (resultBuilder_ == null) {
        return result_ == null ? com.iqexception.fxhelper.api.misc.GetAccessTokenResult.getDefaultInstance() : result_;
      } else {
        return resultBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
     */
    public Builder setResult(com.iqexception.fxhelper.api.misc.GetAccessTokenResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
      } else {
        resultBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
     */
    public Builder setResult(
        com.iqexception.fxhelper.api.misc.GetAccessTokenResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        result_ = builderForValue.build();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
     */
    public Builder mergeResult(com.iqexception.fxhelper.api.misc.GetAccessTokenResult value) {
      if (resultBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          result_ != null &&
          result_ != com.iqexception.fxhelper.api.misc.GetAccessTokenResult.getDefaultInstance()) {
          getResultBuilder().mergeFrom(value);
        } else {
          result_ = value;
        }
      } else {
        resultBuilder_.mergeFrom(value);
      }
      if (result_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
     */
    public Builder clearResult() {
      bitField0_ = (bitField0_ & ~0x00000002);
      result_ = null;
      if (resultBuilder_ != null) {
        resultBuilder_.dispose();
        resultBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
     */
    public com.iqexception.fxhelper.api.misc.GetAccessTokenResult.Builder getResultBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
     */
    public com.iqexception.fxhelper.api.misc.GetAccessTokenResultOrBuilder getResultOrBuilder() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        return result_ == null ?
            com.iqexception.fxhelper.api.misc.GetAccessTokenResult.getDefaultInstance() : result_;
      }
    }
    /**
     * <code>.com.iqexception.fxhelper.api.misc.GetAccessTokenResult result = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iqexception.fxhelper.api.misc.GetAccessTokenResult, com.iqexception.fxhelper.api.misc.GetAccessTokenResult.Builder, com.iqexception.fxhelper.api.misc.GetAccessTokenResultOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.iqexception.fxhelper.api.misc.GetAccessTokenResult, com.iqexception.fxhelper.api.misc.GetAccessTokenResult.Builder, com.iqexception.fxhelper.api.misc.GetAccessTokenResultOrBuilder>(
                getResult(),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.iqexception.fxhelper.api.misc.GetAccessTokenResponse)
  }

  // @@protoc_insertion_point(class_scope:com.iqexception.fxhelper.api.misc.GetAccessTokenResponse)
  private static final com.iqexception.fxhelper.api.misc.GetAccessTokenResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iqexception.fxhelper.api.misc.GetAccessTokenResponse();
  }

  public static com.iqexception.fxhelper.api.misc.GetAccessTokenResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAccessTokenResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAccessTokenResponse>() {
    @java.lang.Override
    public GetAccessTokenResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAccessTokenResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAccessTokenResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iqexception.fxhelper.api.misc.GetAccessTokenResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

