// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: misc.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.misc;

public interface GetAccessTokenResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.misc.GetAccessTokenResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string access_token = 1;</code>
   * @return Whether the accessToken field is set.
   */
  boolean hasAccessToken();
  /**
   * <code>optional string access_token = 1;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>optional string access_token = 1;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();
}
