// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: misc.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.misc;

public interface MsgSubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.misc.MsgSubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the head field is set.
   */
  boolean hasHead();
  /**
   * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
   * @return The head.
   */
  com.iqexception.fxhelper.api.common.MobileRequestHead getHead();
  /**
   * <code>.com.iqexception.fxhelper.api.common.MobileRequestHead head = 1 [(.buf.validate.field) = { ... }</code>
   */
  com.iqexception.fxhelper.api.common.MobileRequestHeadOrBuilder getHeadOrBuilder();

  /**
   * <code>.com.iqexception.fxhelper.api.misc.MsgSubscribeParam param = 2 [(.buf.validate.field) = { ... }</code>
   * @return Whether the param field is set.
   */
  boolean hasParam();
  /**
   * <code>.com.iqexception.fxhelper.api.misc.MsgSubscribeParam param = 2 [(.buf.validate.field) = { ... }</code>
   * @return The param.
   */
  com.iqexception.fxhelper.api.misc.MsgSubscribeParam getParam();
  /**
   * <code>.com.iqexception.fxhelper.api.misc.MsgSubscribeParam param = 2 [(.buf.validate.field) = { ... }</code>
   */
  com.iqexception.fxhelper.api.misc.MsgSubscribeParamOrBuilder getParamOrBuilder();
}
