// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: misc.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.misc;

/**
 * Protobuf type {@code com.iqexception.fxhelper.api.misc.SendWxMessageRequest}
 */
public final class SendWxMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iqexception.fxhelper.api.misc.SendWxMessageRequest)
    SendWxMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SendWxMessageRequest.newBuilder() to construct.
  private SendWxMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendWxMessageRequest() {
    templateId_ = "";
    openId_ = "";
    page_ = "";
    dataJsonString_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SendWxMessageRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_SendWxMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_SendWxMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iqexception.fxhelper.api.misc.SendWxMessageRequest.class, com.iqexception.fxhelper.api.misc.SendWxMessageRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TEMPLATE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object templateId_ = "";
  /**
   * <code>optional string template_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the templateId field is set.
   */
  @java.lang.Override
  public boolean hasTemplateId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string template_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return The templateId.
   */
  @java.lang.Override
  public java.lang.String getTemplateId() {
    java.lang.Object ref = templateId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      templateId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string template_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for templateId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTemplateIdBytes() {
    java.lang.Object ref = templateId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      templateId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPEN_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object openId_ = "";
  /**
   * <code>optional string open_id = 2 [(.buf.validate.field) = { ... }</code>
   * @return Whether the openId field is set.
   */
  @java.lang.Override
  public boolean hasOpenId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string open_id = 2 [(.buf.validate.field) = { ... }</code>
   * @return The openId.
   */
  @java.lang.Override
  public java.lang.String getOpenId() {
    java.lang.Object ref = openId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      openId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string open_id = 2 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for openId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOpenIdBytes() {
    java.lang.Object ref = openId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      openId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object page_ = "";
  /**
   * <code>optional string page = 3;</code>
   * @return Whether the page field is set.
   */
  @java.lang.Override
  public boolean hasPage() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string page = 3;</code>
   * @return The page.
   */
  @java.lang.Override
  public java.lang.String getPage() {
    java.lang.Object ref = page_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      page_ = s;
      return s;
    }
  }
  /**
   * <code>optional string page = 3;</code>
   * @return The bytes for page.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPageBytes() {
    java.lang.Object ref = page_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      page_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATAJSONSTRING_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataJsonString_ = "";
  /**
   * <code>optional string dataJsonString = 4 [(.buf.validate.field) = { ... }</code>
   * @return Whether the dataJsonString field is set.
   */
  @java.lang.Override
  public boolean hasDataJsonString() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string dataJsonString = 4 [(.buf.validate.field) = { ... }</code>
   * @return The dataJsonString.
   */
  @java.lang.Override
  public java.lang.String getDataJsonString() {
    java.lang.Object ref = dataJsonString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataJsonString_ = s;
      return s;
    }
  }
  /**
   * <code>optional string dataJsonString = 4 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for dataJsonString.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataJsonStringBytes() {
    java.lang.Object ref = dataJsonString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataJsonString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, templateId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, openId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, page_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dataJsonString_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, templateId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, openId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, page_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dataJsonString_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iqexception.fxhelper.api.misc.SendWxMessageRequest)) {
      return super.equals(obj);
    }
    com.iqexception.fxhelper.api.misc.SendWxMessageRequest other = (com.iqexception.fxhelper.api.misc.SendWxMessageRequest) obj;

    if (hasTemplateId() != other.hasTemplateId()) return false;
    if (hasTemplateId()) {
      if (!getTemplateId()
          .equals(other.getTemplateId())) return false;
    }
    if (hasOpenId() != other.hasOpenId()) return false;
    if (hasOpenId()) {
      if (!getOpenId()
          .equals(other.getOpenId())) return false;
    }
    if (hasPage() != other.hasPage()) return false;
    if (hasPage()) {
      if (!getPage()
          .equals(other.getPage())) return false;
    }
    if (hasDataJsonString() != other.hasDataJsonString()) return false;
    if (hasDataJsonString()) {
      if (!getDataJsonString()
          .equals(other.getDataJsonString())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTemplateId()) {
      hash = (37 * hash) + TEMPLATE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTemplateId().hashCode();
    }
    if (hasOpenId()) {
      hash = (37 * hash) + OPEN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOpenId().hashCode();
    }
    if (hasPage()) {
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage().hashCode();
    }
    if (hasDataJsonString()) {
      hash = (37 * hash) + DATAJSONSTRING_FIELD_NUMBER;
      hash = (53 * hash) + getDataJsonString().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iqexception.fxhelper.api.misc.SendWxMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iqexception.fxhelper.api.misc.SendWxMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iqexception.fxhelper.api.misc.SendWxMessageRequest)
      com.iqexception.fxhelper.api.misc.SendWxMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_SendWxMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_SendWxMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iqexception.fxhelper.api.misc.SendWxMessageRequest.class, com.iqexception.fxhelper.api.misc.SendWxMessageRequest.Builder.class);
    }

    // Construct using com.iqexception.fxhelper.api.misc.SendWxMessageRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      templateId_ = "";
      openId_ = "";
      page_ = "";
      dataJsonString_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iqexception.fxhelper.api.misc.Misc.internal_static_com_iqexception_fxhelper_api_misc_SendWxMessageRequest_descriptor;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.misc.SendWxMessageRequest getDefaultInstanceForType() {
      return com.iqexception.fxhelper.api.misc.SendWxMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.misc.SendWxMessageRequest build() {
      com.iqexception.fxhelper.api.misc.SendWxMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.misc.SendWxMessageRequest buildPartial() {
      com.iqexception.fxhelper.api.misc.SendWxMessageRequest result = new com.iqexception.fxhelper.api.misc.SendWxMessageRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.iqexception.fxhelper.api.misc.SendWxMessageRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.templateId_ = templateId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.openId_ = openId_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.page_ = page_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.dataJsonString_ = dataJsonString_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iqexception.fxhelper.api.misc.SendWxMessageRequest) {
        return mergeFrom((com.iqexception.fxhelper.api.misc.SendWxMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iqexception.fxhelper.api.misc.SendWxMessageRequest other) {
      if (other == com.iqexception.fxhelper.api.misc.SendWxMessageRequest.getDefaultInstance()) return this;
      if (other.hasTemplateId()) {
        templateId_ = other.templateId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasOpenId()) {
        openId_ = other.openId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasPage()) {
        page_ = other.page_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasDataJsonString()) {
        dataJsonString_ = other.dataJsonString_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              templateId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              openId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              page_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              dataJsonString_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object templateId_ = "";
    /**
     * <code>optional string template_id = 1 [(.buf.validate.field) = { ... }</code>
     * @return Whether the templateId field is set.
     */
    public boolean hasTemplateId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string template_id = 1 [(.buf.validate.field) = { ... }</code>
     * @return The templateId.
     */
    public java.lang.String getTemplateId() {
      java.lang.Object ref = templateId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        templateId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string template_id = 1 [(.buf.validate.field) = { ... }</code>
     * @return The bytes for templateId.
     */
    public com.google.protobuf.ByteString
        getTemplateIdBytes() {
      java.lang.Object ref = templateId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string template_id = 1 [(.buf.validate.field) = { ... }</code>
     * @param value The templateId to set.
     * @return This builder for chaining.
     */
    public Builder setTemplateId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      templateId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string template_id = 1 [(.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTemplateId() {
      templateId_ = getDefaultInstance().getTemplateId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string template_id = 1 [(.buf.validate.field) = { ... }</code>
     * @param value The bytes for templateId to set.
     * @return This builder for chaining.
     */
    public Builder setTemplateIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      templateId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object openId_ = "";
    /**
     * <code>optional string open_id = 2 [(.buf.validate.field) = { ... }</code>
     * @return Whether the openId field is set.
     */
    public boolean hasOpenId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string open_id = 2 [(.buf.validate.field) = { ... }</code>
     * @return The openId.
     */
    public java.lang.String getOpenId() {
      java.lang.Object ref = openId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        openId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string open_id = 2 [(.buf.validate.field) = { ... }</code>
     * @return The bytes for openId.
     */
    public com.google.protobuf.ByteString
        getOpenIdBytes() {
      java.lang.Object ref = openId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        openId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string open_id = 2 [(.buf.validate.field) = { ... }</code>
     * @param value The openId to set.
     * @return This builder for chaining.
     */
    public Builder setOpenId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      openId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string open_id = 2 [(.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearOpenId() {
      openId_ = getDefaultInstance().getOpenId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string open_id = 2 [(.buf.validate.field) = { ... }</code>
     * @param value The bytes for openId to set.
     * @return This builder for chaining.
     */
    public Builder setOpenIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      openId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object page_ = "";
    /**
     * <code>optional string page = 3;</code>
     * @return Whether the page field is set.
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string page = 3;</code>
     * @return The page.
     */
    public java.lang.String getPage() {
      java.lang.Object ref = page_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        page_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string page = 3;</code>
     * @return The bytes for page.
     */
    public com.google.protobuf.ByteString
        getPageBytes() {
      java.lang.Object ref = page_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        page_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string page = 3;</code>
     * @param value The page to set.
     * @return This builder for chaining.
     */
    public Builder setPage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      page_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string page = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPage() {
      page_ = getDefaultInstance().getPage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string page = 3;</code>
     * @param value The bytes for page to set.
     * @return This builder for chaining.
     */
    public Builder setPageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      page_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object dataJsonString_ = "";
    /**
     * <code>optional string dataJsonString = 4 [(.buf.validate.field) = { ... }</code>
     * @return Whether the dataJsonString field is set.
     */
    public boolean hasDataJsonString() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string dataJsonString = 4 [(.buf.validate.field) = { ... }</code>
     * @return The dataJsonString.
     */
    public java.lang.String getDataJsonString() {
      java.lang.Object ref = dataJsonString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataJsonString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string dataJsonString = 4 [(.buf.validate.field) = { ... }</code>
     * @return The bytes for dataJsonString.
     */
    public com.google.protobuf.ByteString
        getDataJsonStringBytes() {
      java.lang.Object ref = dataJsonString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataJsonString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string dataJsonString = 4 [(.buf.validate.field) = { ... }</code>
     * @param value The dataJsonString to set.
     * @return This builder for chaining.
     */
    public Builder setDataJsonString(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataJsonString_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string dataJsonString = 4 [(.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDataJsonString() {
      dataJsonString_ = getDefaultInstance().getDataJsonString();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string dataJsonString = 4 [(.buf.validate.field) = { ... }</code>
     * @param value The bytes for dataJsonString to set.
     * @return This builder for chaining.
     */
    public Builder setDataJsonStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataJsonString_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.iqexception.fxhelper.api.misc.SendWxMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:com.iqexception.fxhelper.api.misc.SendWxMessageRequest)
  private static final com.iqexception.fxhelper.api.misc.SendWxMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iqexception.fxhelper.api.misc.SendWxMessageRequest();
  }

  public static com.iqexception.fxhelper.api.misc.SendWxMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendWxMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<SendWxMessageRequest>() {
    @java.lang.Override
    public SendWxMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SendWxMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendWxMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iqexception.fxhelper.api.misc.SendWxMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

