// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.account;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.account.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 user_id = 1;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
