// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.account;

public interface CreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.account.CreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   * @return The status.
   */
  com.iqexception.fxhelper.api.common.ResponseStatus getStatus();
  /**
   * <code>.com.iqexception.fxhelper.api.common.ResponseStatus status = 1;</code>
   */
  com.iqexception.fxhelper.api.common.ResponseStatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.com.iqexception.fxhelper.api.account.CreateResult result = 2;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.com.iqexception.fxhelper.api.account.CreateResult result = 2;</code>
   * @return The result.
   */
  com.iqexception.fxhelper.api.account.CreateResult getResult();
  /**
   * <code>.com.iqexception.fxhelper.api.account.CreateResult result = 2;</code>
   */
  com.iqexception.fxhelper.api.account.CreateResultOrBuilder getResultOrBuilder();
}
