// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.account;

public interface IncrBalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.account.IncrBalanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 account_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the accountId field is set.
   */
  boolean hasAccountId();
  /**
   * <code>optional int64 account_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return The accountId.
   */
  long getAccountId();

  /**
   * <code>optional string amount = 2 [(.buf.validate.field) = { ... }</code>
   * @return Whether the amount field is set.
   */
  boolean hasAmount();
  /**
   * <code>optional string amount = 2 [(.buf.validate.field) = { ... }</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>optional string amount = 2 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();
}
