// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.account;

public interface TransferRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.account.TransferRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 from_account_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return Whether the fromAccountId field is set.
   */
  boolean hasFromAccountId();
  /**
   * <code>optional int64 from_account_id = 1 [(.buf.validate.field) = { ... }</code>
   * @return The fromAccountId.
   */
  long getFromAccountId();

  /**
   * <code>optional int64 to_account_id = 2 [(.buf.validate.field) = { ... }</code>
   * @return Whether the toAccountId field is set.
   */
  boolean hasToAccountId();
  /**
   * <code>optional int64 to_account_id = 2 [(.buf.validate.field) = { ... }</code>
   * @return The toAccountId.
   */
  long getToAccountId();

  /**
   * <code>optional string amount = 3 [(.buf.validate.field) = { ... }</code>
   * @return Whether the amount field is set.
   */
  boolean hasAmount();
  /**
   * <code>optional string amount = 3 [(.buf.validate.field) = { ... }</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>optional string amount = 3 [(.buf.validate.field) = { ... }</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();
}
