// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pay.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.pay;

public interface Acct2wxResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.pay.Acct2wxResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 pay_id = 1;</code>
   * @return Whether the payId field is set.
   */
  boolean hasPayId();
  /**
   * <code>optional int64 pay_id = 1;</code>
   * @return The payId.
   */
  long getPayId();
}
