// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.order;

/**
 * Protobuf type {@code com.iqexception.fxhelper.api.order.GetOrderListRequest}
 */
public final class GetOrderListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iqexception.fxhelper.api.order.GetOrderListRequest)
    GetOrderListRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetOrderListRequest.newBuilder() to construct.
  private GetOrderListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetOrderListRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetOrderListRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iqexception.fxhelper.api.order.Order.internal_static_com_iqexception_fxhelper_api_order_GetOrderListRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iqexception.fxhelper.api.order.Order.internal_static_com_iqexception_fxhelper_api_order_GetOrderListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iqexception.fxhelper.api.order.GetOrderListRequest.class, com.iqexception.fxhelper.api.order.GetOrderListRequest.Builder.class);
  }

  private int bitField0_;
  public static final int SHOP_ID_FIELD_NUMBER = 1;
  private long shopId_ = 0L;
  /**
   * <code>optional int64 shop_id = 1;</code>
   * @return Whether the shopId field is set.
   */
  @java.lang.Override
  public boolean hasShopId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 shop_id = 1;</code>
   * @return The shopId.
   */
  @java.lang.Override
  public long getShopId() {
    return shopId_;
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private long userId_ = 0L;
  /**
   * <code>optional int64 user_id = 2;</code>
   * @return Whether the userId field is set.
   */
  @java.lang.Override
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 user_id = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_ = 0;
  /**
   * <code>optional int32 status = 3;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 status = 3;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int FROM_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp from_;
  /**
   * <code>optional .google.protobuf.Timestamp from = 4;</code>
   * @return Whether the from field is set.
   */
  @java.lang.Override
  public boolean hasFrom() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .google.protobuf.Timestamp from = 4;</code>
   * @return The from.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getFrom() {
    return from_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : from_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp from = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getFromOrBuilder() {
    return from_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : from_;
  }

  public static final int TO_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp to_;
  /**
   * <code>optional .google.protobuf.Timestamp to = 5;</code>
   * @return Whether the to field is set.
   */
  @java.lang.Override
  public boolean hasTo() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .google.protobuf.Timestamp to = 5;</code>
   * @return The to.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTo() {
    return to_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : to_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp to = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getToOrBuilder() {
    return to_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : to_;
  }

  public static final int OFFSET_FIELD_NUMBER = 6;
  private int offset_ = 0;
  /**
   * <code>optional int32 offset = 6;</code>
   * @return Whether the offset field is set.
   */
  @java.lang.Override
  public boolean hasOffset() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 offset = 6;</code>
   * @return The offset.
   */
  @java.lang.Override
  public int getOffset() {
    return offset_;
  }

  public static final int LIMIT_FIELD_NUMBER = 7;
  private int limit_ = 0;
  /**
   * <code>optional int32 limit = 7;</code>
   * @return Whether the limit field is set.
   */
  @java.lang.Override
  public boolean hasLimit() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional int32 limit = 7;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, shopId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, userId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, status_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getFrom());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getTo());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(6, offset_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt32(7, limit_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, shopId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, userId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, status_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFrom());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTo());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, offset_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, limit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iqexception.fxhelper.api.order.GetOrderListRequest)) {
      return super.equals(obj);
    }
    com.iqexception.fxhelper.api.order.GetOrderListRequest other = (com.iqexception.fxhelper.api.order.GetOrderListRequest) obj;

    if (hasShopId() != other.hasShopId()) return false;
    if (hasShopId()) {
      if (getShopId()
          != other.getShopId()) return false;
    }
    if (hasUserId() != other.hasUserId()) return false;
    if (hasUserId()) {
      if (getUserId()
          != other.getUserId()) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (getStatus()
          != other.getStatus()) return false;
    }
    if (hasFrom() != other.hasFrom()) return false;
    if (hasFrom()) {
      if (!getFrom()
          .equals(other.getFrom())) return false;
    }
    if (hasTo() != other.hasTo()) return false;
    if (hasTo()) {
      if (!getTo()
          .equals(other.getTo())) return false;
    }
    if (hasOffset() != other.hasOffset()) return false;
    if (hasOffset()) {
      if (getOffset()
          != other.getOffset()) return false;
    }
    if (hasLimit() != other.hasLimit()) return false;
    if (hasLimit()) {
      if (getLimit()
          != other.getLimit()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasShopId()) {
      hash = (37 * hash) + SHOP_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getShopId());
    }
    if (hasUserId()) {
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
    }
    if (hasFrom()) {
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
    }
    if (hasTo()) {
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
    }
    if (hasOffset()) {
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset();
    }
    if (hasLimit()) {
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iqexception.fxhelper.api.order.GetOrderListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iqexception.fxhelper.api.order.GetOrderListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iqexception.fxhelper.api.order.GetOrderListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iqexception.fxhelper.api.order.GetOrderListRequest)
      com.iqexception.fxhelper.api.order.GetOrderListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iqexception.fxhelper.api.order.Order.internal_static_com_iqexception_fxhelper_api_order_GetOrderListRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iqexception.fxhelper.api.order.Order.internal_static_com_iqexception_fxhelper_api_order_GetOrderListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iqexception.fxhelper.api.order.GetOrderListRequest.class, com.iqexception.fxhelper.api.order.GetOrderListRequest.Builder.class);
    }

    // Construct using com.iqexception.fxhelper.api.order.GetOrderListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFromFieldBuilder();
        getToFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      shopId_ = 0L;
      userId_ = 0L;
      status_ = 0;
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      to_ = null;
      if (toBuilder_ != null) {
        toBuilder_.dispose();
        toBuilder_ = null;
      }
      offset_ = 0;
      limit_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iqexception.fxhelper.api.order.Order.internal_static_com_iqexception_fxhelper_api_order_GetOrderListRequest_descriptor;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.order.GetOrderListRequest getDefaultInstanceForType() {
      return com.iqexception.fxhelper.api.order.GetOrderListRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.order.GetOrderListRequest build() {
      com.iqexception.fxhelper.api.order.GetOrderListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iqexception.fxhelper.api.order.GetOrderListRequest buildPartial() {
      com.iqexception.fxhelper.api.order.GetOrderListRequest result = new com.iqexception.fxhelper.api.order.GetOrderListRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.iqexception.fxhelper.api.order.GetOrderListRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.shopId_ = shopId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userId_ = userId_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.status_ = status_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.from_ = fromBuilder_ == null
            ? from_
            : fromBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.to_ = toBuilder_ == null
            ? to_
            : toBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.offset_ = offset_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.limit_ = limit_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iqexception.fxhelper.api.order.GetOrderListRequest) {
        return mergeFrom((com.iqexception.fxhelper.api.order.GetOrderListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iqexception.fxhelper.api.order.GetOrderListRequest other) {
      if (other == com.iqexception.fxhelper.api.order.GetOrderListRequest.getDefaultInstance()) return this;
      if (other.hasShopId()) {
        setShopId(other.getShopId());
      }
      if (other.hasUserId()) {
        setUserId(other.getUserId());
      }
      if (other.hasStatus()) {
        setStatus(other.getStatus());
      }
      if (other.hasFrom()) {
        mergeFrom(other.getFrom());
      }
      if (other.hasTo()) {
        mergeTo(other.getTo());
      }
      if (other.hasOffset()) {
        setOffset(other.getOffset());
      }
      if (other.hasLimit()) {
        setLimit(other.getLimit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              shopId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              status_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getFromFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getToFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              offset_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              limit_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long shopId_ ;
    /**
     * <code>optional int64 shop_id = 1;</code>
     * @return Whether the shopId field is set.
     */
    @java.lang.Override
    public boolean hasShopId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 shop_id = 1;</code>
     * @return The shopId.
     */
    @java.lang.Override
    public long getShopId() {
      return shopId_;
    }
    /**
     * <code>optional int64 shop_id = 1;</code>
     * @param value The shopId to set.
     * @return This builder for chaining.
     */
    public Builder setShopId(long value) {

      shopId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 shop_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearShopId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      shopId_ = 0L;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>optional int64 user_id = 2;</code>
     * @return Whether the userId field is set.
     */
    @java.lang.Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 user_id = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>optional int64 user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <code>optional int32 status = 3;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>optional int32 status = 3;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {

      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000004);
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp from_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> fromBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp from = 4;</code>
     * @return Whether the from field is set.
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp from = 4;</code>
     * @return The from.
     */
    public com.google.protobuf.Timestamp getFrom() {
      if (fromBuilder_ == null) {
        return from_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : from_;
      } else {
        return fromBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp from = 4;</code>
     */
    public Builder setFrom(com.google.protobuf.Timestamp value) {
      if (fromBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        from_ = value;
      } else {
        fromBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp from = 4;</code>
     */
    public Builder setFrom(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (fromBuilder_ == null) {
        from_ = builderForValue.build();
      } else {
        fromBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp from = 4;</code>
     */
    public Builder mergeFrom(com.google.protobuf.Timestamp value) {
      if (fromBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          from_ != null &&
          from_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getFromBuilder().mergeFrom(value);
        } else {
          from_ = value;
        }
      } else {
        fromBuilder_.mergeFrom(value);
      }
      if (from_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp from = 4;</code>
     */
    public Builder clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000008);
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp from = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getFromBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getFromFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp from = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getFromOrBuilder() {
      if (fromBuilder_ != null) {
        return fromBuilder_.getMessageOrBuilder();
      } else {
        return from_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : from_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp from = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getFromFieldBuilder() {
      if (fromBuilder_ == null) {
        fromBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getFrom(),
                getParentForChildren(),
                isClean());
        from_ = null;
      }
      return fromBuilder_;
    }

    private com.google.protobuf.Timestamp to_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> toBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp to = 5;</code>
     * @return Whether the to field is set.
     */
    public boolean hasTo() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp to = 5;</code>
     * @return The to.
     */
    public com.google.protobuf.Timestamp getTo() {
      if (toBuilder_ == null) {
        return to_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : to_;
      } else {
        return toBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp to = 5;</code>
     */
    public Builder setTo(com.google.protobuf.Timestamp value) {
      if (toBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        to_ = value;
      } else {
        toBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp to = 5;</code>
     */
    public Builder setTo(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (toBuilder_ == null) {
        to_ = builderForValue.build();
      } else {
        toBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp to = 5;</code>
     */
    public Builder mergeTo(com.google.protobuf.Timestamp value) {
      if (toBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          to_ != null &&
          to_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getToBuilder().mergeFrom(value);
        } else {
          to_ = value;
        }
      } else {
        toBuilder_.mergeFrom(value);
      }
      if (to_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp to = 5;</code>
     */
    public Builder clearTo() {
      bitField0_ = (bitField0_ & ~0x00000010);
      to_ = null;
      if (toBuilder_ != null) {
        toBuilder_.dispose();
        toBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp to = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getToBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getToFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp to = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getToOrBuilder() {
      if (toBuilder_ != null) {
        return toBuilder_.getMessageOrBuilder();
      } else {
        return to_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : to_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp to = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getToFieldBuilder() {
      if (toBuilder_ == null) {
        toBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTo(),
                getParentForChildren(),
                isClean());
        to_ = null;
      }
      return toBuilder_;
    }

    private int offset_ ;
    /**
     * <code>optional int32 offset = 6;</code>
     * @return Whether the offset field is set.
     */
    @java.lang.Override
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 offset = 6;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }
    /**
     * <code>optional int32 offset = 6;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(int value) {

      offset_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 offset = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      bitField0_ = (bitField0_ & ~0x00000020);
      offset_ = 0;
      onChanged();
      return this;
    }

    private int limit_ ;
    /**
     * <code>optional int32 limit = 7;</code>
     * @return Whether the limit field is set.
     */
    @java.lang.Override
    public boolean hasLimit() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 limit = 7;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }
    /**
     * <code>optional int32 limit = 7;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {

      limit_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 limit = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      bitField0_ = (bitField0_ & ~0x00000040);
      limit_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.iqexception.fxhelper.api.order.GetOrderListRequest)
  }

  // @@protoc_insertion_point(class_scope:com.iqexception.fxhelper.api.order.GetOrderListRequest)
  private static final com.iqexception.fxhelper.api.order.GetOrderListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iqexception.fxhelper.api.order.GetOrderListRequest();
  }

  public static com.iqexception.fxhelper.api.order.GetOrderListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetOrderListRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetOrderListRequest>() {
    @java.lang.Override
    public GetOrderListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetOrderListRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetOrderListRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iqexception.fxhelper.api.order.GetOrderListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

