// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.rest.proto

// Protobuf Java Version: 3.25.0
package com.iqexception.fxhelper.api.rest.account;

public interface GetAccountResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iqexception.fxhelper.api.rest.account.GetAccountResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 account_id = 1;</code>
   * @return Whether the accountId field is set.
   */
  boolean hasAccountId();
  /**
   * <code>optional int64 account_id = 1;</code>
   * @return The accountId.
   */
  long getAccountId();

  /**
   * <code>optional int64 user_id = 2;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional int64 user_id = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>optional string balance = 3;</code>
   * @return Whether the balance field is set.
   */
  boolean hasBalance();
  /**
   * <code>optional string balance = 3;</code>
   * @return The balance.
   */
  java.lang.String getBalance();
  /**
   * <code>optional string balance = 3;</code>
   * @return The bytes for balance.
   */
  com.google.protobuf.ByteString
      getBalanceBytes();

  /**
   * <code>optional int32 status = 4;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>optional int32 status = 4;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>optional .google.protobuf.Timestamp created_at = 5;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp created_at = 5;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp created_at = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>optional .google.protobuf.Timestamp updated_at = 6;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp updated_at = 6;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp updated_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();
}
