admin.registry.address=nacos://host.docker.internal:8848
admin.config-center=nacos://host.docker.internal:8848
admin.metadata-report.address=nacos://host.docker.internal:8848
admin.root.user.name=root
admin.root.user.password=root
#admin.check.signSecret=86295dd0c4ef69a1036b0b0c15158d77